### ISSUE TITLE
null reference to renderer in v2.7.8

### ISSUE THREAD

**Issue by jiangliu** [cytoscape/cytoscape.js#1499] opened 2016-08-21 04:40 UTC
With v2.7.8, it triggers following violation after reinitializing cytoscape. And a simple protection could fix the issue by checking "if (renderer)" before calling "renderer.notify( params );" in function notify at line 7245 in file cytoscape.js. Error messages as below.
Thanks!

Cannot read property 'notify' of null
隐藏详细
TypeError: Cannot read property 'notify' of null at corefn.notify (http://127.0.0.1:8080/x5/UI2/v_8c3422a0b2d148ae8a2fd8f22767054dl_zh_CNs_desktopd_pc/etrack/common/plugin/cytoscape/cytoscape.js:7246:13) at elesfn.rtrigger (http://127.0.0.1:8080/x5/UI2/v_8c3422a0b2d148ae8a2fd8f22767054dl_zh_CNs_desktopd_pc/etrack/common/plugin/cytoscape/cytoscape.js:3644:15) at elesfn.updateStyle (http://127.0.0.1:8080/x5/UI2/v_8c3422a0b2d148ae8a2fd8f22767054dl_zh_CNs_desktopd_pc/etrack/common/plugin/cytoscape/cytoscape.js:5090:16) at null.select (http://127.0.0.1:8080/x5/UI2/v_8c3422a0b2d148ae8a2fd8f22767054dl_zh_CNs_desktopd_pc/etrack/common/plugin/cytoscape/cytoscape.js:5402:19) at mouseupHandler (http://127.0.0.1:8080/x5/UI2/v_8c3422a0b2d148ae8a2fd8f22767054dl_zh_CNs_desktopd_pc/etrack/common/plugin/cytoscape/cytoscape.js:15138:20)

**Comment by maxkfranz** [comment] 2016-08-22 17:07
Are you trying to reuse a `.destroy()`ed instance?  Once an instance is destroyed, it can't be used anymore.

Would you please paste your re-init code here?

**Comment by jiangliu** [comment] 2016-08-22 17:32
I never call .destroy:) Just call showSpaceCy.prototype.showRoom() and alike repeatly.
	showSpaceCy.prototype.showRoom = function(row) {
		var self = this, eles = this.generateRoomEles(row);
		if (this.uiInfo.autoSize) {
			this.$container.height(this.yOffset * 2 + "px");
			this.xPanBy = 0;
			this.yPanBy = 0;
			this.uiInfo.padding = 10;
		} else {
			this.xPanBy = -30;
			this.yPanBy = 25;
		}
		this.initUI({container : this.container,
					 elements : eles.cnodes,
					 style : roomStyle,
					 layout : { name : 'preset', fit : autoFitRoom, padding : self.uiInfo.padding },
		 			 minZoom : 0.2,
					 maxZoom : 3,
					 selectionType : 'additive',
					 wheelSensitivity: 0.4,
					 ready : function(evt) {
						 if (autoFitRoom) {
							 evt.cy.panBy({x:self.xPanBy,y:self.yPanBy}).$('node').lock();
							 //Trick to work around a issue of cytoscape
							 if (!self.uiInfo.readyCalled)
								 setTimeout(function(){ self.fit(); }, 1);
						 } else {
							 evt.cy.pan({x:self.xOffset,y:self.yOffset + 50}).$('node').lock();
						 }
					 },
					}, 'node.parent', 'node.device');
		return eles.tnodes;
	};

**Comment by jiangliu** [comment] 2016-08-22 17:38
One more note, the above code works with a previous version of cytoscape, but I can't figure the specific version number now.

**Comment by maxkfranz** [comment] 2016-08-22 19:37
I can't reproduce this.  I just tried initialising on an already used div, and there's no error.  Would you please create a Jsbin that reproduces your issue?  You can just fork one of the demos to save time.

**Comment by jiangliu** [comment] 2016-08-23 18:35
The .destroy() is implicitly called, please refer to attached image for call stack.
![Uploading cytoscape-1499.png…]()

**Comment by jiangliu** [comment] 2016-08-23 18:37
![Uploading cytoscape-1499.png…]()
![Uploading cytoscape-1499.png…]()

**Comment by jiangliu** [comment] 2016-08-23 18:39
sorry, failed to upload screen shot, so the call stack is
cyWrapper.init() -> cytoscape() -> Core -> util.extend.destroy() ->corefn.destroyRenderer(),
then _private.renderer is set to null, thus cause null reference later.

**Comment by maxkfranz** [comment] 2016-08-23 18:44
Unfortunately, that doesn't help.  That call stack is normal.

You must be doing something specific, because overwriting an instance works fine for me every time.  I need to see a demo that reproduces the issue.

**Comment by jiangliu** [comment] 2016-08-23 18:50
I feel it has some relationships to mouse event handling. We implemented a file directory like structure. Upon a mouse click event on an element, it will reinitialize the cytoscope instance to redraw child objects.
And we have enabled click, select, unselect etc on all cytoscape objects.

**Comment by maxkfranz** [comment] 2016-08-23 18:59
All event handling is removed on destroy.

Without a demo, it will be near impossible for me to reproduce your issue.  I don't have the time to try to recreate your scenario by trail and error, so unless you provide a demo there's nothing I can do to help you.

**Comment by Zigur** [comment] 2016-09-13 13:11
I am having a similar issue using 2.7.8 (2.7.6 works fine, instead) :

Uncaught TypeError: Cannot read property 'recalculateRenderedStyle' of nullelesfn.boundingBox 
@ dimensions.js:758 getFitViewport 
@ viewport.js:250 fit 
@ viewport.js:201(anonymous function)  
@ cose.js:156

You can have  a look at it, [here](https://preview.biosharing.org/react-home/#/graph/bsg-c000024?_k=0r3c2a), at least until I will not reset the old dependency

**Comment by maxkfranz** [comment] 2016-09-14 19:18
@Zigur Yes, I'd be very interested in seeing a demo for this, as I haven't been able to reproduce the issue.

**Comment by EyMaddis** [comment] 2016-09-19 15:46
This happens when `destroy()` is called in between frames.
For example the line within cose.js (156) which @Zigur mentions runs asynchronously due to `requestAnimationFrame`:
https://github.com/cytoscape/cytoscape.js/blob/75a15818da5662c9e78930b157f8745885aca6a8/src/extensions/layout/cose.js#L154-L155

**Comment by maxkfranz** [comment] 2016-09-19 20:23
Thanks for the info, @EyMaddis.

It looks like to do a complete fix, a few changes are needed:

(1) APIs that the core or elements can call on the renderer must have a check whether the renderer was destroyed.  This might not be strictly needed for some ops, but it's safer in general.

(2) Every instance where an API in (1) is consumed (i.e. via `cy.renderer()`), the consumer must check the renderer reference.  It would be more accurate to have a renderer-is-destroyed check, but this would complicate the null/nop renderer.  Checking for null means that we might have silent errors in future, but it's probably a fair trade-off.

(3) The `.notify()` check should really also see whether the core is destroyed.  That's not possible until 3.1 with @EyMaddis' PR #1527.  I made an issue to track the future improvement https://github.com/cytoscape/cytoscape.js/issues/1528

**Comment by maxkfranz** [comment] 2016-09-19 20:25
Try the snapshot : http://js.cytoscape.org/download/cytoscape.js-snapshot-dc6bb7f291-1474316715767.zip

Let me know if it works for you or if you have any issues with it.  

Thanks

**Comment by maxkfranz** [comment] 2016-09-26 14:55
2.7.10 is being released today.  Since this is working as far as my testing shows, I'm closing this.  If anyone runs into an issue, please update us all here.

**Closed by maxkfranz** 2016-09-26 14:55 UTC
Labels: bug

**Comment by marimeireles** [comment] 2020-02-21 13:51
Hey @maxkfranz are you still the one to ping?
I'm porting Cytoscape to Jupyter Widgets and ran in to a similar problem. If you're interested I can write an example and explain how to reproduce the error. If you are, would be better to open a new issue or continue from here?
Thanks!

**Comment by maxkfranz** [comment] 2020-02-24 15:42
If the issue can be reproduced independently of Jupyter, then it's probably something that can be addressed within the library.  If not, it might be a problem with Jupyter.  In either case, let's start with a new issue and a reproducible test case.
