### ISSUE TITLE
IndexSizeError in  CanvasRenderer.prototype.drawInscribedImage

### ISSUE THREAD

**Issue by jerchap** [cytoscape/cytoscape.js#785] opened 2014-12-30 20:59 UTC
On IE 10, I'm using the breadthfirst layout, and my nodes are using a background image.  Sometimes, if I refresh the page I get an IndexSizeError exception in the   CanvasRenderer.prototype.drawInscribedImage function on context.DrawImage.

I believe the issue is that for some reason, the image might not be fully loaded when context.drawImage is called.  The drawInscribedImage function is called by CanvasRenderer.prototype.drawNode which attempts to check that the image load is complete, but as a test, if wrap the context.drawImage call drawInscribedImage in a try/catch and add a delay followed by a second attempt at context.drawImage it appears to work fine.

Example:
try
{
&nbsp;&nbsp;&nbsp;&nbsp;context.drawImage( img, 0, 0, img.width, img.height, x, y, w, h );
}
catch (e)
{
&nbsp;&nbsp;&nbsp;&nbsp;setTimeout(function ()
&nbsp;&nbsp;&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;context.drawImage(img, 0, 0, img.width, img.height, x, y, w, h);
&nbsp;&nbsp;&nbsp;&nbsp;}, 1);
}

By putting a breakpoint in the catch, I know that the IndexSizeError is occurring, and visual inspection shows that all nodes have background images.

**Comment by maxkfranz** [comment] 2015-01-02 22:39
I suspect there's a problem in IE10 itself, as the code should draw an image only after it's loaded.  I'll take a look; thanks

**Comment by jeremychapman** [comment] 2015-01-02 23:10
Just a note,  my images are being loaded from a database, not from the file system, so this is probably adding some latency.  Essentially what I have is the url being referenced from the graph is an http address serviced by a web server.  That page actually loads the image data from a database and streams it out to the browser.  It's effectively no different from referencing a file system as the data is exactly the same, but it does add some latency.

**Comment by maxkfranz** [comment] 2015-01-08 18:04
@jeremychapman Is this an IE-only issue for you, or is it a general issue in your case when you load via database?

**Comment by jeremychapman** [comment] 2015-01-08 20:50
I load from databases using this method in many solutions, never an error.  I really think the fact that a database is the source of the image data is a red herring.    The reason I mentioned it is because it may be introducing latency, and latency could be something that causes this error to manifest.

To elaborate, my image would be served up from an http request (captured with fiddler).

The actual http request would look like this:
GET http://mysite.com/imagehandler.ashx?ID=22 HTTP/1.1
Accept: */*
Accept-Language: en-CA
User-Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.3; WOW64; Trident/7.0; .NET4.0E; .NET4.0C; InfoPath.3; .NET CLR 3.5.30729; .NET CLR 2.0.50727; .NET CLR 3.0.30729)
Accept-Encoding: gzip, deflate
Connection: Keep-Alive
DNT: 1
Host: mysite.com
Cookie: ASP.NET_SessionId=dnutvf412suku1rdwm1r2xsd
Authorization: Negotiate TlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGA4AlAAAADw==





The http response would look like this:
HTTP/1.1 200 OK
Cache-Control: private
Content-Type: image/pjpeg
Server: Microsoft-IIS/7.5
X-AspNet-Version: 4.0.30319
Persistent-Auth: true
X-Powered-By: ASP.NET
Date: Thu, 08 Jan 2015 20:43:15 GMT
Content-Length: 530

�PNG
_
���
IHDR���_���___���_��a���_gAMA����7_�����_tEXtSoftware�Adobe ImageReadyq�e<��_�IDAT8˥�?O�@_�_�_T�X_�FC�NJH�_~_�����&�


It’s no different to how a web page would reference an image, except for under the hood the image comes from a database not the file system, but to the caller it wouldn’t know the difference

**Comment by maxkfranz** [comment] 2015-01-08 21:21
@jeremychapman @jerchap Would you please post a `console.dir(img)` for me in the error cases?  I don't have access to IE10 and I don't think I'll be able to put together a DB example just right now.

If there's something in there that I could use to detect your error cases, I can create a snapshot build for you to try out that should work around the issue.  Thanks

**Comment by maxkfranz** [comment] 2015-06-23 20:21
I've been able to reproduce this, more or less.  Assigning to 2.4.3.  Unfortunately, a try-catch seems the only way to work around this -- even if the image is fully and properly loaded.  It's really strange.

**Closed** 2015-06-23 20:22 UTC
Labels: browser-bug, bug, renderer
