### ISSUE TITLE
Run breadthfirst layout right after cose layout will cause Maximum call stack size exceeded

### ISSUE THREAD

**Issue by tongbin** [cytoscape/cytoscape.js#1577] opened 2016-10-18 02:35 UTC
The call stack is listed below

![image](https://cloud.githubusercontent.com/assets/8870302/19462306/6ef02382-951e-11e6-802c-eddbd3b7bff7.png)

**Comment by tongbin** [comment] 2016-10-18 02:43
Looks like the layoutstart event is triggered too much time;

**Comment by josephst** [comment] 2016-10-27 02:51
@tongbin Re not animating: telling cose to animate will animate the force-directed algorithm (rather than animating the move to the finished layout, like other algorithms do). With a small graph, cose will run so quickly that it looks like there's no animation. This also explains why cose doesn't have an animationDuration property like most other layouts: the duration is however long it takes to run the algorithm.

**Comment by maxkfranz** [comment] 2016-11-09 20:41
I don't think there's a bug here, or at least I'm not able to reproduce.  If you're using `cy.on('layoutstop', runAnotherLayout)` you'll naturally get stuck in a loop and overflow the stack -- because you'll run a new layout whenever any layout is finished.  Did you use `.on()` instead of `.one()`?

**Comment by maxkfranz** [comment] 2016-11-29 15:41
Can't reproduce; closing

**Closed by maxkfranz** 2016-11-29 15:41 UTC

**Comment by Krewn** [comment] 2018-07-17 03:48
Have you tried to reproduce with a larger graph, perhaps one larger than half the maximum size?
