### ISSUE TITLE
Canvas will crash in Firefox when zooming with large BoundingBox width/height

### ISSUE THREAD

**Issue by ngkahinkeith** [cytoscape/cytoscape.js#3283] opened 2024-10-10 02:39 UTC
**Environment info**

- Cytoscape.js version : 3.30.2
- Browser/Node.js & version : Firefox 115.10.0 esr (64-bit) & Firefox 131.0 (64-bit)

**Current (buggy) behaviour**
In Firefox, when using Cytoscape.js to a graph with large boundingbox width/height value, the browser encounters an error `Uncaught NS_ERROR_FAILURE` (in esr version) / `InvalidStateError: OffscreenCanvasRenderingContext2D.scale: Canvas could not create basic draw target.` (in 131.0 version) when zooming in or out, leading to a crash on canvas. This issue does not occur with smaller value or in other browsers like Chrome.

**Desired behaviour**
Cytoscape should be able to handle large boundingbox value for nodes without error on firefox, allowing for normal zooming interactions.

**Minimum steps to reproduce**
1. Initialize a Cytoscape instance with a container.
2. Add two nodes, where the second node has a large y position value (In my case, greater than 8159).
3. Connect the nodes with an edge. (Optional)
4. Attempt to zoom in or out.

or https://jsfiddle.net/yhor9x4q/

**For reviewers**

_Reviewers should ensure that the following tasks are carried out for incorporated issues:_

- [ ] Ensure that the reporter has included a reproducible demo.  They can easily fork this JSBin demo: http://jsbin.com/fiqugiq
- [ ] The issue has been associated with a corresponding [milestone](https://github.com/cytoscape/cytoscape.js/milestones).
- [ ] The commits have been incorporated into the corresponding branches.  Bug-fix patches go on
    - [ ] `master`,
    - [ ] `unstable`, and
    - [ ] the previous feature release branch (e.g. `1.1.x` if the current release is 1.2).
- [ ] The issue has been labelled as a [`bug`](https://github.com/cytoscape/cytoscape.js/labels/bug), if necessary.

**Comment by mikekucera** [comment] 2024-10-15 20:45
This is already fixed on unstable. It looks like a duplicate of #3258.

**Closed by mikekucera** 2024-10-15 20:45 UTC
Labels: bug

**Comment by ngkahinkeith** [comment] 2024-10-21 07:38
Sorry for late reply, it seems I messed up the node_module linking on my side. And the problem is gone after I use the unstable branch. Thanks for your help
