### ISSUE TITLE
Feature request: Edge merging

### ISSUE THREAD

**Issue by Fransooijs** [cytoscape/cytoscape.js#811] opened 2015-01-28 14:14 UTC
I would like to request a feature for the merging of edges, where two or more edges meet before arriving at the target node.
I currently implement this by adding an extra node that is invisible (width and height of 0).
However, it would be really neat if this was a built-in feature in cytoscape.js.  

Example image:
![edge_merging](https://cloud.githubusercontent.com/assets/10688021/5938957/93138c52-a6f7-11e4-9f01-20807d396e66.png)

Example code:
https://gist.github.com/Fransooijs/50ad067ee323a64df7de

**Comment by maxkfranz** [comment] 2015-03-23 18:49
Issue : Events and app scope

Say I tap the edge by the arrow.  Which edge gets the event?  All of them?  One of them?  None of them?

**Comment by chrtannus** [comment] 2015-06-16 17:42
Depends on https://github.com/cytoscape/cytoscape.js/issues/359

**Comment by maxkfranz** [comment] 2015-09-25 19:58
I don't think this should be supported with separate edges, given the issues with semantics.  Hyperedges should produce the same visual effect.  Closing as duplicate of https://github.com/cytoscape/cytoscape.js/issues/959

**Closed by maxkfranz** 2015-09-25 19:58 UTC
Labels: enhancement, performance, renderer, style
