### ISSUE TITLE
Box select when starting over a node if modifier key down

### ISSUE THREAD

**Issue by ugurdogrusoz** [cytoscape/cytoscape.js#1583] opened 2016-10-20 12:06 UTC
I think it's very critical that one should be able to start a box selection (Ctrl and/or Shift + select) within a compound (sometimes compound nodes are rather big like many processes within a cellular compartment). Currently this starts a drag of the compound!

**Comment by maxkfranz** [comment] 2016-11-09 21:02
Possible solutions:

(1) When a modifier key is down (e.g. shift), a node can't be dragged if box selection is enabled.  Instead, box selection starts.

(2) When a modifier key is down (e.g. shift), a *compound* node can't be dragged if box selection is enabled.  Instead, box selection starts.

I would lean towards (1), because it's more consistent.  What do you think?

**Comment by ugurdogrusoz** [comment] 2016-11-10 04:18
I agree I think (1) is better

**Comment by maxkfranz** [comment] 2016-11-14 19:52
(1) implemented on unstable

**Comment by maxkfranz** [comment] 2016-11-14 19:57
Closing since it's implemented; re-open if need be

**Comment by ugurdogrusoz** [comment] 2017-03-08 11:19
@markgoffin This is great! But there is a problem. I realize that the rule is all nodes/edges overlapping with our selection box get selected. But if we need to select a proper subset of children of a compound and say move them, we can't do this using this box selection since the compound itself is selected! If the box selection starts and ends inside a compound, can we perhaps make an exception and not select the compound? I can't image a scenario where the user is indeed interested in selecting both the compound and a proper subset of the compound's children.

**Comment by maxkfranz** [comment] 2017-03-08 22:01
There are a couple of approaches I see:

(1) Select a parent only if the box encloses it.

(2) Select a parent if there's any overlap with the box, unless the box is contained by the parent.

Case (1) avoids selection of parents who overlap each other for the case you mentioned, whereas (2) does not.  Case (1) makes selecting children by box generally easier than (2).  However, (1) is not consistent with how box selection works for non-compound nodes.  

What do you think?

**Comment by ugurdogrusoz** [comment] 2017-03-09 02:11
In fact (2) is exactly what I tried to describe. We only add an exception to the current box selection that we do not select the parent when the box is contained by the parent. Thanks.

**Closed** 2017-05-02 17:16 UTC
Labels: priority-2-medium

**Comment by ugurdogrusoz** [comment] 2017-05-23 06:48
@maxkfranz @mj3cheun We upgraded our application (http://www.cs.bilkent.edu.tr/~ivis/ChiSE_daily/) to use Cytoscape.js 3.1 but box selection inside a compound still selects the compound as well?

**Comment by maxkfranz** [comment] 2017-05-23 16:06
I just tested it and it's working in the 3.1 release.  You're probably using an older release

**Comment by maxkfranz** [comment] 2017-05-23 16:07
It activates the compound during the gesture, which is a bit distracting and could be removed, but it doesn't select the parent.

**Comment by ugurdogrusoz** [comment] 2017-05-25 11:43
I confirm it's fine

**Comment by shean42** [comment] 2017-10-08 07:39
While testing this (great) feature I came across the issue that a box selection in a compound node does not seem to work if the parent is ungrabified. My assumption is that this is not by design?
