### ISSUE TITLE
Breadthfirst layout- not working with new cytoscapeJS version

### ISSUE THREAD

**Issue by AjitPS** [cytoscape/cytoscape.js#986] opened 2015-06-23 15:37 UTC
Hi, I am using the latest version of cytoscapeJS. However, the ````breadthfirst```` layout is not working anymore. When I use it in my graph, I get the following error:
````Uncaught TypeError: Cannot read property 'index' of undefined````

This used to work in the previous version of cytoscapeJS.

My code for the <b>breadthfirst</b> layout is below:

````
function set_Breadthfirst_Layout(eles) {
     var bf_Layout= { name: 'breadthfirst', fit: true, directed: true, padding: 10, 
     circle: false, boundingBox: undefined, avoidOverlap: true, handleDisconnected: true,
     maximalAdjustments: 0, animate: false, roots: undefined, ready: 
     undefined, stop: undefined, spacingFactor: 1.75 };

eles.layout(bf_Layout);

**Comment by maxkfranz** [comment] 2015-06-23 16:09
I can't reproduce this on regular or compound graphs.  I'd need the graph that has problems.

**Comment by maxkfranz** [comment] 2015-07-13 21:16
Closing until reproducible

**Closed by maxkfranz** 2015-07-13 21:16 UTC

**Comment by sasoripathos** [comment] 2019-08-05 18:32
I also find this problem if I set directed to be true

**Comment by snuup** [comment] 2021-02-23 10:14
thank you @sasoripathos - i suddenly encountered such 

     Uncaught TypeError: Cannot read property 'index' of undefined

errors and finally concluded that this is a bug in cytoscape. setting directed to false the errors went away. 

@maxkfranz maybe i find the time and can isolate the problem.
