### ISSUE TITLE
cxttap does not properly work in version 3.30.1

### ISSUE THREAD

**Issue by Grim-Reaperr** [cytoscape/cytoscape.js#3265] opened 2024-08-07 07:56 UTC
**Before you post**

There is an issue with the cxttap event

**Environment info**

- Cytoscape.js version : 3.30.1
- Browser/Node.js & version :  Chrome 

**Current (buggy) behaviour**

_What does the bug do?_

cxttap no longer works after a left-click was done anywhere in the cy div, possibly because the event can no longer be called or the nodes can no longer be found

**Desired behaviour**

_What do you expect Cytoscape.js to do instead?_

It should still be working after making a left click

**Minimum steps to reproduce**

_What do you need to do to reproduce the issue?_

Create a cy-Graph in HTML
Create an event-trigger that listens to the 'cxttap' property and assign it an easily monitorable function (e.g. console log)
On site load, right click anywhere --> the cxttap gets properly recognized as many times as it is used
Left click anywhere after site load, cxttap no longer gets recognized. 

**For reviewers**

The issue can be seen in the following demos and are no longer present after downgrading to 3.29.1:
https://ivis-at-bilkent.github.io/cytoscape.js-cise/demo/demo.html
https://cytoscape.org/cytoscape.js-cxtmenu/

_Reviewers should ensure that the following tasks are carried out for incorporated issues:_

- [ ] Ensure that the reporter has included a reproducible demo.  They can easily fork this JSBin demo: http://jsbin.com/fiqugiq
- [ ] The issue has been associated with a corresponding [milestone](https://github.com/cytoscape/cytoscape.js/milestones).
- [ ] The commits have been incorporated into the corresponding branches.  Bug-fix patches go on
    - [ ] `master`,
    - [ ] `unstable`, and
    - [ ] the previous feature release branch (e.g. `1.1.x` if the current release is 1.2).
- [ ] The issue has been labelled as a [`bug`](https://github.com/cytoscape/cytoscape.js/labels/bug), if necessary.

**Comment by maxkfranz** [comment] 2024-08-07 13:54
Duplicate of:

- #3262

**Closed** 2024-08-07 13:59 UTC
Labels: bug
