### ISSUE TITLE
Background/Border for edge labels are not placed correctly

### ISSUE THREAD

**Issue by butimo** [cytoscape/cytoscape.js#1519] opened 2016-09-07 13:02 UTC
using text-background and -border styles for edges will not work as expected. edge label is overlapping/miss-placed. I have build a sample in jsfiddle (http://fiddle.jshell.net/7x3twm5j/1/)

'text-background-opacity': 1,
'text-background-color': '#ffffff',
'text-background-shape': 'rectangle',
'text-border-style': 'solid',
'text-border-opacity': 1,
'text-border-width': '1px',
'text-border-color': 'darkgray'

**Comment by maxkfranz** [comment] 2016-09-07 14:47
Duplicate of https://github.com/cytoscape/cytoscape.js/issues/1513

Fixed in master and will be released with [2.7.9](https://github.com/cytoscape/cytoscape.js/issues?q=is%3Aopen+is%3Aissue+milestone%3A2.7.9)

**Closed by maxkfranz** 2016-09-07 14:47 UTC
