### ISSUE TITLE
MouseMove event select elements even with boxSelectionEnabled disabled

### ISSUE THREAD

**Issue by MauricioDentz** [cytoscape/cytoscape.js#910] opened 2015-04-15 12:13 UTC
I have an issue that the box selection occurs even when the boxSelectionEnabled is disabled.
This happens because the mosemove event dont consider the boxSelectionEnabled value.
This verification occurs on the mouseUp event, but on that point the elements are already selected.

Case senario: Disable boxSelectionEnabled, try do to a selection and before releasing the mouse enable the boxSelectionEnabled. When the mouseup is triggered the elements will be selected.

**Comment by maxkfranz** [comment] 2015-04-15 15:53
Have you tried changing gesture state only when not in the gesture, i.e. after `mouseup`?  Even if additional checks were added to `mousemove`, by changing state during the gesture you would almost certainly run into problems later during `mouseup` handling by mutating the enabled state of a gesture midgesture.

**Comment by MauricioDentz** [comment] 2015-04-15 16:48
I get what you are saying.
In my case I don't change the gesture state during the mousemove, but in my custom mouseup and mousedown events.
My custom mousedown changes the state and the mouseup restores the previous state. The problem is that the custom mouseup event runs before the cytoscape event, causing the inconsistency.
I can workaround to avoid this, but the state must be consistent and "locked" during the hole process of down, move and up events, because they work as one single event (IMO).

**Comment by maxkfranz** [comment] 2015-04-15 17:31
My initial thought is that resolving this in a general way would require checking all gesture combinations throughout the event handlers -- though maybe this is only an issue because of the shared pan/boxselect state where time is used to select between them.

If this requires significant changes, I'll have to push this to 2.4 instead of 2.3.x.  Though since the unstable/2.4 branch is more or less finished codewise (sans some docs stuff etc), you could use a build off of that if you want to pull in the change quickly.  In any case, I'll take a look.

**Comment by MauricioDentz** [comment] 2015-04-15 18:10
I'll take a look at that. Thank you for your time.

**Comment by maxkfranz** [comment] 2015-04-24 21:18
@MauricioDentz 

Snapshot : http://js.cytoscape.org/download/cytoscape.js-snapshot-517d0b6471-1429897013031.zip

This may fix it for you, though I can't reproduce the issue -- so I couldn't say for sure.

**Comment by MauricioDentz** [comment] 2015-04-27 12:14
@maxkfranz 
Works flawlessly. Seems faster to, but I need to do more tests.
Thanks!

**Comment by maxkfranz** [comment] 2015-04-27 12:51
Good to hear.  I'll close this for now, and please re-open if you notice any issues.

**Closed by maxkfranz** 2015-04-27 12:51 UTC
