### ISSUE TITLE
Context menu bug

### ISSUE THREAD

**Issue by MarcoGrandeRDTech** [cytoscape/cytoscape.js#3266] opened 2024-08-07 14:38 UTC
**Environment info**

- Cytoscape.js version : cytoscape: 3.30.1,
    cytoscape-context-menus: 4.1.0

- Browser/Node.js & version :
- node version 18.20.0
- Multiple browsers (Mozilla, Chrome, Edge)

_What does the bug do?_

I can't open the context menu after left clicking on my cytoscape grid, the same behaviour happens on the context-menu demo available online. https://ivis-at-bilkent.github.io/cytoscape.js-context-menus/demo.html and also https://cytoscape.org/cytoscape.js-cxtmenu/

**Desired behaviour**
The context menu should appear after left clicking.

**Minimum steps to reproduce**

Step1: right click on node -> correctly opens the context menu
Step2: left click anywhere on the cytoscape grid
Step 3: right click on node -> context menu doesn't appear anymore

**Comment by maxkfranz** [comment] 2024-08-07 14:45
Duplicate of:

- #3262

**Closed** 2024-08-08 15:34 UTC
Labels: bug
