### ISSUE TITLE
Mouseover events fire on neighbouring edges covered by nodes when the edge is assigned with 'top' for 'z-compound-depth' style

### ISSUE THREAD

**Issue by soomin-maeng** [cytoscape/cytoscape.js#2171] opened 2018-08-22 18:05 UTC
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.2.16
- Browser/Node.js & version : firefox 61.0.2, chrome 68.0.3440.106, edge 42.17134.1.0

**Current (buggy) behaviour**

With a mouseover event assigned to edges to change z-compound-depth to 'top', the neighboring edges that are covered by nodes also change its z-compound-depth to 'top' when the mouse moves over them (move across the node).
So, when there are a lot of edges under a node, it becomes hard to tap the node since edges (with the event triggered, it appears on the top of the node) get selected instead.

**Desired behaviour**

The mouseover event should not be triggered to those neighboring edges that are covered by the node.

**Minimum steps to reproduce**

With the style added to edge.hover:
.selector('edge.hover')
      .css({
        'z-compound-depth': 'top',
      })

cy.on('mouseover', 'edge', function(e) {
  e.target.addClass('hover');
});
cy.on('mouseout', 'edge', function(e) {
  e.target.removeClass('hover');
});

**Comment by maxkfranz** [comment] 2018-09-04 19:38
Would you please make a clear demo that shows the issue?

**Comment by soomin-maeng** [comment] 2018-09-13 23:28
Sure, I attached a zip file that contains a video of the bug behaviour and the javascript file. The javascript file is the modified version of one of the demo on js.cytoscape.org to show the behaviour. Sorry for the confusion.
[bug.zip](https://github.com/cytoscape/cytoscape.js/files/2381340/bug.zip)

**Comment by maxkfranz** [comment] 2018-09-25 17:32
You've put the edges over top of the nodes.  The element that gets the event is whatever is on top at the position you click, so it doesn't look like a bug here.

**Comment by dwitvliet** [comment] 2018-10-04 23:33
Maybe I can clarify: The z-order of the elements in the example should be: `edge.hover` > `node` > `edge`. Therefore, the cursor should be possible to move off the hovered edge onto the node. However, that does not happen. Instead, the cursor lands on the non-hovered edge behind the node, making that edge into a hovered edge. Effectively, the z-order becomes `edge.hover` > `edge` > `node` whenever _any_ edge is hovered.

**Comment by maxkfranz** [comment] 2018-10-09 17:40
> Maybe I can clarify: The z-order of the elements in the example should be: edge.hover > node > edge. Therefore, the cursor should be possible to move off the hovered edge onto the node. However, that does not happen. Instead, the cursor lands on the non-hovered edge behind the node, making that edge into a hovered edge. Effectively, the z-order becomes edge.hover > edge > node whenever any edge is hovered.

Thank you for the explanation.

This is not reproducible in v3.2.17.  The provided demo is for v2 -- e.g. `cyTarget` is used.  The v2 line is no longer supported: http://blog.js.cytoscape.org/2018/06/26/ending-support-of-2.x/

I modified the example to work in v3, and everything works as expected.  This issue will be closed until a reproducible demo is provided for v3.

**Comment by maxkfranz** [comment] 2018-10-09 17:44
Note that the labels do not normally cause events, like mouseover or click.  So hovering over a node's label is not expected to do anything normally.  See http://js.cytoscape.org/#style/events

**Comment by dwitvliet** [comment] 2018-10-17 00:12
I have managed to reproduce the behavior on v3.2.17.

All you need to reproduce it are the following lines:

```javascript
var cy = cytoscape({
  container: document.querySelector('#cy'),
  layout: {'name': 'grid', 'row': 3},
  style: [
    {
      selector: 'edge.hover',
      css: {
        'z-compound-depth': 'top',
        'line-color': '#FF0000'
      }
    }
  ],
  elements: {
    nodes: [
      {data: {id: 'n1'}}, {data: {id: 'n2'}}, {data: {id: 'n3'}},
      {data: {id: 'n4'}}, {data: {id: 'n5'}}, {data: {id: 'n6'}},
      {data: {id: 'n7'}}, {data: {id: 'n8'}}, {data: {id: 'n9'}}
    ],
    edges: [
      {data: {id: 'e1', source: 'n1', target: 'n5'}},
      {data: {id: 'e2', source: 'n2', target: 'n5'}},
      {data: {id: 'e3', source: 'n3', target: 'n5'}},
      {data: {id: 'e4', source: 'n4', target: 'n5'}},
      {data: {id: 'e5', source: 'n6', target: 'n5'}},
      {data: {id: 'e6', source: 'n7', target: 'n5'}},
      {data: {id: 'e7', source: 'n8', target: 'n5'}},
      {data: {id: 'e8', source: 'n9', target: 'n5'}}
    ]
  }
});

cy.on('mouseover', 'edge', function(e) {
  e.target.addClass('hover');
});
cy.on('mouseout', 'edge', function(e) {
  e.target.removeClass('hover');
});
```

The result is a network where the center node is almost impossible to select because the edges appear on top of it.

I've attached a working example with both the html and js file.

[bug_v3.2.17.zip](https://github.com/cytoscape/cytoscape.js/files/2485352/bug_v3.2.17.zip)

**Comment by maxkfranz** [comment] 2018-10-29 15:52
There may have been a reason for excluding compound depth from the edge override check in the hit test -- for real compound graphs.

3.2.19 is released with the change, but if this creates unforeseen issues for compound graphs we'll have to re-evaluate.  For non-compound graphs, you should never need to use `z-compound-depth` at all:  Manual `z-index` for all elements suffices.

**Closed by maxkfranz** 2018-10-29 15:52 UTC
Labels: bug

**Comment by dwitvliet** [comment] 2018-10-29 16:17
Thank you for fixing it so promptly. Everything seems to behave as it should on our end in 3.2.19, but we'll let you know if anything odd comes up.
