### ISSUE TITLE
Visual Style Demo Modification Does Not Display Color

### ISSUE THREAD

**Issue by markcarter01** [cytoscape/cytoscape.js#913] opened 2015-04-23 15:10 UTC
I have been playing around with the 'Visual Style' demo but the application is not displaying the node color or text outline. Here are the modifications I have made:

I have replaced the node and edges with my variables but left the format the same, e.g. id, name, weight, faveColor and faveShape. The colors were changed as were the shapes. When run against IE, FF, and GC, I get a fault pointing to: the Cytoscape.js file:

if( !flatProp ){ printMappingErr(); }
      flatProp.mapping = prop; // keep a reference to the mapping
      prop = flatProp; // the flattened (mapped) property is the one we want
      break; 

The error message states:

Unhandled exception at line 5764, column 7 in http://localhost:52970/javascript/cytoscape.js
0x800a138f - JavaScript runtime error: Unable to set property 'mapping' of undefined or null reference

When I comment the css for (node) width, background-color, text-outline-color, and color, the application execute in the fashion expected. I may be doing something wrong but can't figure out what it is. The concept works in Cytoscape and Cytoscape Web. Code listed below:

 <script>
    $(function () { 

        $('#cy').cytoscape({
            layout: {
                name: 'cose',
                padding: 10
            },

            style: cytoscape.stylesheet()
              .selector('node')
                .css({
                    'shape': 'data(faveShape)',
                    //'background-color': 'blue',
                    //'width': 'mapData(weight, 40, 80, 20, 60)',
                    'content': 'data(name)',
                    'text-valign': 'center',
                    'text-outline-width': 1,
                    //'text-outline-color': 'data(faveColor)',
                    //'color': 'data(faveColor)'
                })
              .selector(':selected')
                .css({
                    'border-width': 3,
                    'border-color': '#333'
                })
              .selector('edge')
                .css({
                    'opacity': 0.666,
                    //'width': 'mapData(strength, 70, 100, 2, 6)',
                    'target-arrow-shape': 'triangle',
                    'target-arrow-color': 'data(faveColor)',
                    'source-arrow-shape': 'circle',
                    'source-arrow-color': 'data(faveColor)',
                    'line-color': 'data(faveColor)',

                    //.selector('edge.questionable')
                    //  .css({
                    //      'line-style': 'dotted',
                    //      'target-arrow-shape': 'diamond'
                    //  })
                    //.selector('.faded')
                    //  .css({
                    //      'opacity': 0.25,
                    //      'text-opacity': 0
                    //  }),

                    //'target-arrow-color': 'data(faveColor)'
                }),

            elements: {
                nodes: [
                  { data: { id: '1', name: 'Ford Motor Company', weight: '80', faveColor: '#0040FF', faveShape: 'rectangle' } },
                  { data: { id: '2', name: 'General Motors LLC', weight: '50', faveColor: '#FE642E', faveShape: 'rectangle' } },
                  { data: { id: '3', name: 'BMW of North America', weight: '50', faveColor: '#D358F7', faveShape: 'rectangle' } },
                  { data: { id: '4', name: 'FCA USA', weight: '50', faveColor: '#F5D0A9', faveShape: 'rectangle' } },
                  { data: { id: '5', name: 'Mercedes-Benz USA', weight: '50', faveColor: '#BDBDBD', faveShape: 'rectangle' } },
                  { data: { id: '6', name: 'Mitsubishi Fuso Truck', weight: '50', faveColor: '#F6CECE', faveShape: 'rectangle' } },
                  { data: { id: '7', name: 'Nissan North America', weight: '50', faveColor: '#58FA58', faveShape: 'rectangle' } },
                  { data: { id: '8', name: 'Volkswagen Group of America', weight: '50', faveColor: '#81F7F3', faveShape: 'rectangle' } },
                  { data: { id: '10', name: 'BMW', weight: '40', faveColor: '#D358F7', faveShape: 'roundrectangle' } },
                  { data: { id: '11', name: 'MINI', weight: '40', faveColor: '#D358F7', faveShape: 'roundrectangle' } },
                  { data: { id: '12', name: 'Chrysler', weight: '40', faveColor: '#FE642E', faveShape: 'roundrectangle' } },
                  { data: { id: '13', name: 'Ford', weight: '40', faveColor: '#0040FF', faveShape: 'roundrectangle' } },
                  { data: { id: '14', name: 'Lincoln', weight: '40', faveColor: '#0040FF', faveShape: 'roundrectangle' } },
                  { data: { id: '15', name: 'Chevrolet', weight: '40', faveColor: '#FE642E', faveShape: 'roundrectangle' } },
                  { data: { id: '16', name: 'Mercedes-Benz', weight: '40', faveColor: '#BDBDBD', faveShape: 'roundrectangle' } },
                  { data: { id: '17', name: 'Mitsubishi', weight: '40', faveColor: '#F6CECE', faveShape: 'roundrectangle' } },
                  { data: { id: '18', name: 'Nissan', weight: '40', faveColor: '58FA58', faveShape: 'roundrectangle' } },
                  { data: { id: '19', name: 'Volkswagen', weight: '40', faveColor: '81F7F3', faveShape: 'roundrectangle' } },

                ],
                edges: [
                  { data: { source: '1', target: '13', faveColor: '#6FB1FC', strength: 90 } },
                  { data: { source: '1', target: '14', faveColor: '#6FB1FC', strength: 70 } },
                  { data: { source: '2', target: '15', faveColor: '#EDA1ED', strength: 95 } },
                  { data: { source: '3', target: '10', faveColor: '#EDA1ED', strength: 60 } },
                  { data: { source: '3', target: '11', faveColor: '#86B342', strength: 100 } },
                  { data: { source: '4', target: '12', faveColor: '#86B342', strength: 100 } },
                  { data: { source: '5', target: '16', faveColor: '#86B342', strength: 100 } },
                  { data: { source: '6', target: '17', faveColor: '#F5A45D', strength: 90 } },
                  { data: { source: '7', target: '18', faveColor: '#F5A45D', strength: 90 } },
                  { data: { source: '8', target: '19', faveColor: '#F5A45D', strength: 90 } },

                ]
            },

            ready: function () {
                window.cy = this;
            }
        });

    });
    </script>

**Comment by maxkfranz** [comment] 2015-04-27 13:58
Please post your code as a gist, jsbin, or similar.  I'm unable to reproduce this with a precise specification of what your code is doing.

**Comment by maxkfranz** [comment] 2015-09-03 23:03
Closing

Not reproducible, and the reporter is unresponsive

**Closed by maxkfranz** 2015-09-03 23:03 UTC
