### ISSUE TITLE
When the label is at bottom, the background is not correct

### ISSUE THREAD

**Issue by tongbin** [cytoscape/cytoscape.js#1517] opened 2016-09-06 03:01 UTC
I've shown the label bottom of the node with background color.

![bottom_label_with_bg](https://cloud.githubusercontent.com/assets/8870302/18260543/42f05e00-7421-11e6-9ea5-c0e73fd1c061.jpg)

Looks like we need to add a line in the 

/src/extensions/renderer/canvas/drawing-label-text.js line 275

bgY -= textH;

**Comment by tongbin** [comment] 2016-09-06 03:19
I've checked out the latest code and find out this issue has been fixed, so there is an latency between the npm repository and the master code?

**Comment by maxkfranz** [comment] 2016-09-06 18:16
Master gets published to npm when all the issues assigned to the current bugfix milestone are closed: https://github.com/cytoscape/cytoscape.js/milestones

Looks like a duplicate of https://github.com/cytoscape/cytoscape.js/issues/1503 for 2.7.9

**Closed by maxkfranz** 2016-09-06 18:16 UTC

**Comment by maxkfranz** [comment] 2016-09-07 14:46
Actually duplicate of https://github.com/cytoscape/cytoscape.js/issues/1513

**Comment by tongbin** [comment] 2016-09-08 01:09
Thanks for replying.
