### ISSUE TITLE
"free" event doesn't fire if you right click during drag and drop

### ISSUE THREAD

**Issue by Ciappone** [cytoscape/cytoscape.js#3005] opened 2022-03-28 07:55 UTC
**Environment info**

- Cytoscape.js version : 3.20.0
- Browser/Node.js & version : Google Chrome v. 99

**Current (buggy) behaviour**

as per title, if you right click with mouse during drag and drop, the node will be set free without firing the event "free".

**Desired behaviour**

the free event should be fired aniway

**Minimum steps to reproduce**

start dragging a node e right click before drop.

**Comment by maxkfranz** [comment] 2022-04-20 18:32
Please provide a reproducible test case according to the issue template, including a code sample that reproduces the issue.  [A JSBin](http://jsbin.com/fiqugiq) can be forked to easily provide a code sample.  You may want to log events or show them in a div and demonstrate how they may violate your expectations.

A GIF or video would also help

**Comment by maxkfranz** [comment] 2022-05-06 17:59
I tried your demo.  It seems like there's the assumption that the user is cancelling the gesture by pressing the right mouse button.  So, the node isn't explicitly freed by the user.  So, there's a few things to consider:

(1) There's not currently a cancellation event for dragging.  It's not clear that cancelling should be the same event as a user-intended 'free' event.  If it's always the same event, how do you tell the difference?

(2) When the cancellation occurs should be carefully considered.  It could be on the second button's 'mousedown' or on its 'mouseup'.

(3) Cancellation doesn't seem to be possible on some devices, like the on the Mac trackpad.  An analogous case may be pressing with a second finger on touch devices, like the iPad.

(4) Given that this seems to be a request for some sort of new drag cancelling support with new events -- see (1) -- this may be something that should be planned as a new feature rather than as something included in a patch release.

(5) There's accessibility to consider.  It could be that we shouldn't support cancellation at all.  If someone isn't very dextrous with a mouse, it's easy to accidentally hit the extra right mouse button while dragging.  In that case, it might be better to ignore the right mouse button rather than cancelling.  As in (3), if we go this way, the behaviour should be made consistent for touch device users.

**Comment by Ciappone** [comment] 2022-05-13 13:11
Thanks for your considerations, do you think this behavior can be fixed in an upcoming release, as you explained in (5)?

**Comment by maxkfranz** [comment] 2022-06-07 14:30
Let’s simplify this to consider only the mouse events.  The touch case is more complex, and it seems qualitatively different after some analysis.

So, basically the new behaviour would be this:  If we’re in the middle of a desktop (i.e. mouse) drag gesture, then all right mouse button events should be ignored.

**Comment by maxkfranz** [comment] 2022-06-07 14:31
@chrtannus, would you take a look at this one?

**Comment by maxkfranz** [comment] 2024-06-11 21:49
@chrtannus, unless you have this one in-progress I'll grab this one

**Comment by chrtannus** [comment] 2024-06-11 21:51
Go ahead, Max. Thanks!

**Comment by maxkfranz** [comment] 2024-06-18 14:55
@chrtannus & @Ciappone, would you verify the fix in the `fix/free-dnd-3005` branch?

**Comment by maxkfranz** [comment] 2024-06-18 14:56
Expected new behaviour: 

> So, basically the new behaviour would be this: If we’re in the middle of a desktop (i.e. mouse) drag gesture, then all right mouse button events should be ignored.

**Comment by chrtannus** [comment] 2024-06-19 20:24
@maxkfranz, I tested the fix on my MacBook with a mouse and it worked as expected -- pressing or clicking the right button did not interrupt any of these actions: panning, dragging a node, drag-selecting nodes with the selection rectangle (holding shift).

**Comment by maxkfranz** [comment] 2024-06-20 14:30
Great.  Let's close this once the patch has been applied to all the branches

**Closed** 2024-06-27 13:41 UTC
Labels: bug, pinned
