### ISSUE TITLE
Strange squished fonts on font size change

### ISSUE THREAD

**Issue by blazespinnaker** [cytoscape/cytoscape.js#2754] opened 2020-09-26 02:32 UTC
**Environment info**
chrome, Version 85.0.4183.121 (Official Build) (64-bit)
- Cytoscape.js version :
https://unpkg.com/cytoscape/dist/cytoscape.min.js
- Browser/Node.js & version :

**Current (buggy) behaviour**

code:

```

<!doctype html>

<html>

<head>
    <title>Tutorial 1: Getting Started</title>
    <script src="https://unpkg.com/cytoscape/dist/cytoscape.min.js"></script>
</head>

<style>
    #cy {
        width: 100%;
        height: 100%;
        position: absolute;
        top: 0px;
        left: 0px;
    }

</style>

<body>
    <div id="cy"></div>
    <script>
      var cy = cytoscape({
        container: document.getElementById('cy'),
        style: [
            {
              selector: 'node',
              style: {
                'content': 'data(name)'
              }
            },

        {
              selector: '.large',
              style   : {
                  'font-size': '80px'
              }
          }],

      });

    for (var i =0;i<100;i++) {
        cy.add({data:{name: "n"+i}});
    }
    cy.layout({name: 'random'}).run();
    </script>
</body>
</html>

The bug really boils down to one line, calling 

cy.elements().addClass("large")

Which I did in the console.

**Comment by blazespinnaker** [comment] 2020-09-26 02:34
![image](https://user-images.githubusercontent.com/2188809/94328293-160e3b80-ff66-11ea-80ed-2cc3662c9ba1.png)

**Comment by blazespinnaker** [comment] 2020-09-26 02:35
The problem was occurring in a lot of different contexts, but that was the simplest repro I could come up with.

**Comment by blazespinnaker** [comment] 2020-09-26 03:57
fwiw, it works (though the labels vanish quickly on zoom out) in https://github.com/cytoscape/cytoscape.js/commit/75171c2a8a9c7b359df4f9d5af901abc9312ec8c and the regression appears in the child commit - https://github.com/cytoscape/cytoscape.js/commit/8b9167d53c77e5560b0e4b81f219d30af8caf6a9

**Comment by blazespinnaker** [comment] 2020-09-26 19:23
I reverted to  100728ab73a729b9e9b3684f2d0e22fb410d7d26 build and it works very well.

**Comment by blazespinnaker** [comment] 2020-09-26 19:46
Regression is starting in https://github.com/cytoscape/cytoscape.js/commit/75171c2a8a9c7b359df4f9d5af901abc9312ec8c, child commit seems to aggravate it.

**Comment by maxkfranz** [comment] 2020-09-28 13:55
Closing, as this is a duplicate of #2752.  Refer to #2752 for updates.  Thanks for the example

**Closed by maxkfranz** 2020-09-28 13:55 UTC
