### ISSUE TITLE
Calling cytoscape with a json containing compound nodes causes TypeError

### ISSUE THREAD

**Issue by curupaco** [cytoscape/cytoscape.js#806] opened 2015-01-22 12:36 UTC
Steps to reproduce:

1. Save a json from some graph with compound nodes (http://jsbin.com/gist/5b192c88616af2f75344?js,output)
2. load the saved json ( `$('#cy').cytoscape(JSON.parse(json))`)

TypeError occurs
`Uncaught TypeError: Cannot read property 'bypass' of undefined`

The property giving the error was `height`.

**Comment by maxkfranz** [comment] 2015-01-30 20:42
Can't reproduce exactly; maybe this is related? https://github.com/cytoscape/cytoscape.js/issues/813

**Comment by curupaco** [comment] 2015-02-02 10:35
I think it was related. With the code from 2.3.8 on the debug page it occurs, but can't reproduce with the code from master too

**Comment by maxkfranz** [comment] 2015-02-02 15:59
I'm getting other errors though when I go through steps like on #813.  I suspect there is another issue with style serialisation and/or style application on compound nodes in specific cases...

**Comment by maxkfranz** [comment] 2015-02-02 16:00
I think you can workaround the issue for now by using your own, separate JSON style and assigning with that to `initOptions.style`.  The serialised one is going down a path with a bug, it seems.

**Comment by maxkfranz** [comment] 2015-02-03 18:21
Also related: #817

I think these should all fix the issue overall.

Would you please try master or this snapshot and confirm it goes OK for you?

Snapshot: http://js.cytoscape.org/download/cytoscape.js-snapshot-8631d477ec-1422987551340.zip

**Comment by curupaco** [comment] 2015-02-03 18:30
Sure, I can test it tomorrow morning.

**Comment by maxkfranz** [comment] 2015-02-03 19:39
Cool; closing for now since it works for me and I want to have the milestone ready for release ASAP.

We can reopen if you notice anything wrong.  Thanks

**Closed by maxkfranz** 2015-02-03 19:39 UTC
Labels: bug

**Comment by curupaco** [comment] 2015-02-04 10:48
Thanks Max. It works perfectly

**Comment by maxkfranz** [comment] 2015-02-05 17:00
Good; time to release then
