### ISSUE TITLE
cytoscape Snap to Grid On Release & Snap to Grid During Drag: ON issue

### ISSUE THREAD

**Issue by Rishi0405** [cytoscape/cytoscape.js#2358] opened 2019-04-16 13:19 UTC
Hi,

I am using cytoscape and cytoscape.js-grid-guide plugins,
When snap to grid during drag and snap to grid On release is enabled and the node is dragged, the links are misplaced sometimes

![snaptogridIssue](https://user-images.githubusercontent.com/18022748/56212760-4ca90c80-6078-11e9-825b-50d506082676.JPG)

Thanks,
Rishi

**Comment by Rishi0405** [comment] 2019-04-16 13:57
It happens with the latest version 3.5.3

**Comment by maxkfranz** [comment] 2019-04-16 19:31
Please post issues with extensions in the extension's repo.  It's not clear where the issue is, and the author of the extension would be the best one to identify it.

**Comment by maxkfranz** [comment] 2019-04-17 13:47
Possibly related: https://github.com/cytoscape/cytoscape.js/issues/2355

Try the snapshot

**Comment by Rishi0405** [comment] 2019-04-29 12:22
Hi Max,

Thanks for the quick update. But I am still facing the issue with Cytoscape and guidegrid, in version 3.5.4. I just turned off the setting in guidegrid and it works fine. I am not sure where the issue is.

Thanks,
Rishi

**Comment by maxkfranz** [comment] 2019-04-29 18:15
You should create an issue in the extension's repo so the extension author can determine what the issue is.  I'm closing this for now, and it can be re-opened if it's determined to be a core issue.

**Closed by maxkfranz** 2019-04-29 18:15 UTC
