### ISSUE TITLE
JSON file not opening in Cystoscape desktop

### ISSUE THREAD

**Issue by nandankita** [cytoscape/cytoscape.js#1018] opened 2015-07-24 18:24 UTC
Hi,
I have generated the JSON of my image by calling,
cy.json()

It returns the JSON, which I am saving in a file. I tried to open my JSON file, which has "preset layout" and "compound nodes"; in Cytoscape(Version: 3.2.1) Desktop version, but it doesn't open. I suppose the user who is generating the JSON, will want to open the JSON file in Cytoscape and try to render it there.
It doesn't even show any error while trying to open in cytoscape(Version: 3.2.1). Please refer the attachment for details. Please let me know if you need any more clarifications on this or if I need to change anything in my code.

Thanks,
Ankita

![screen shot 2015-07-24 at 2 12 26 pm](https://cloud.githubusercontent.com/assets/9012937/8881484/1cb39b7c-320e-11e5-85ef-d0a0fcf2b5ab.png)

![screen shot 2015-07-24 at 2 21 41 pm](https://cloud.githubusercontent.com/assets/9012937/8881632/5c56c79e-320f-11e5-98cb-30f314f376a6.png)

**Comment by maxkfranz** [comment] 2015-07-24 20:20
@keiono Could you take a look at this?  The user might not be generating the JSON your plugin expects, but there should probably be an error message either way.

Maybe it makes sense to move this ticket to Cytoscape desktop.

**Comment by keiono** [comment] 2015-07-24 21:30
I'll try and see what happens.  The output JSON file looks fine to me, so it can be an Cytoscape Desktop issue.

**Comment by keiono** [comment] 2015-07-24 21:35
What happens if you manually add "data" element in the JSON?


{
  data: {name: 'foo'},
  elements: [],
  .
  .
  .
}

**Comment by nandankita** [comment] 2015-07-24 23:52
I tried manually adding the data in JSON as follow:

 {"elements": {
    "nodes": [
      { "data": { "id": "a"} },
      { "data": { "id": "b" } },
      { "data": { "id": "c"} },
      { "data": { "id": "d" } },
      { "data": { "id": "e" } },
      { "data": { "id": "f"} }
    ],
    "edges": [
      { "data": { "id": "ad", "source": "a", "target": "d" } },
      { "data": { "id": "eb", "source": "e", "target": "b" } }
      
    ]
  }
 }

And tried opening it in Cytoscape desktop, but the same thing happens, an error dialogue box without any error. Does Cytoscape desktop needs different parameters? or anything else needs to be included in this JSON?

**Comment by keiono** [comment] 2015-07-24 23:58
Oh, sorry.  I mean adding data:{} for network, not nodes/edges.

{
  "data": {"name": "my network name" },
  elements:[ . . .]
}

This defines name of the network, etc.  Cytoscape Desktop depends on that network-level information, and it maybe the cause of this issue.

**Comment by nandankita** [comment] 2015-07-25 00:44
Okay sorry, I misunderstood it.  So I generated a JSON from Cytoscape desktop as follow:
{
  "format_version" : "1.0",
  "generated_by" : "cytoscape-3.2.1",
  "target_cytoscapejs_version" : "~2.1",
  "data" : {
    "shared_name" : "My Network",
    "name" : "My Network",
    "SUID" : 104,
    "__Annotations" : [ ],
    "selected" : true
  },
  "elements" : {
    "nodes" : [ {
      "data" : {
        "id" : "114",
        "shared_name" : "Node1",
        "name" : "a",
        "SUID" : 114,
        "selected" : false
      },
      "position" : {
        "x" : 0.0,
        "y" : 0.0
      },
      "selected" : false
    } ],
    "edges" : [ ]
  }
}

I manually edited it to as follow:
{
  "data" : {
    "name" : "My Network",
  },
  "elements" : {
    "nodes" : [ {
      "data" : {
        "id" : "1",
        "name" : "a",
      },
    } ],
    "edges" : [ ]
  }
}

But the edited version doesn't work. I think that a manual version of JSON won't work with Cytoscape desktop, since it needs all those parameters. But on the other hand if I am generating a JSON from Cytoscape.js that should be supported in desktop version as well. Or I would request a feature in Cytoscape.js to have a function which can generate the JSON, excatly as supported by the desktop version.

**Comment by maxkfranz** [comment] 2015-07-27 15:37
Firstly: @nandankita   I think you're running into a separate bug, that Cytoscape desktop errors out if you give it a graph with only one node (or just several nodes).  This happens for sure with JSON import, but possibly other formats as well.

Secondly: @keiono  Is it not possible to support import/export of vanilla JSON in Cy desktop, e.g. `cy.json()` and `cy.elements().jsons()`?  All that desktop metadata, like `SUID` could be automatically generated for the user.

**Comment by maxkfranz** [comment] 2015-07-27 15:40
@keiono This may mean that an extra check may be needed in the importer.  `elements` may be a map of `elements: { nodes: [ ... ], edges: [ ... ] }` or an array `elements: [ { group: 'nodes', ... } ]`.  The export can use either style.

**Comment by keiono** [comment] 2015-07-27 16:30
@maxkfranz 

Yes, I think the JSON reader in Cytoscape desktop should seamlessly work with Cytoscape.js outputs.  I've just added new ticket:

https://code.cytoscape.org/redmine/issues/3213

Will be fixed in the next release.

**Comment by keiono** [comment] 2015-07-27 17:09
OK, I think I found the issue.

CYtoscape JSON reader is very strict because it uses default settings for Jackson JSON library for Java, and it does not allow comma at the end of elements in array.  for example, this does NOT work:

```json
[
    "name": "foo",
]
```

but this does:
```json
[
    "name": "foo"
]
```

And here is the fixed JSON:

https://gist.github.com/b96057b9ea11c2602317

Hope this helps.

**Comment by nandankita** [comment] 2015-07-27 17:21
Thank you @keiono & @maxkfranz. This is a great help! This new JSON file works perfectly fine with Cytoscape desktop.

Thanks a lot for responding so quickly on this!

**Comment by nandankita** [comment] 2015-07-27 17:41
I tried with the JSON file generated by cy.json(). If we manually add the data, i.e.
{
"data": {"name": "My Network"},
"elements":{}
}
we can open the file in Cytoscape desktop, but only the issue is that it doesn't import the exact layout and colors which is there with cytoscape.js.

Hope the next version will address this issue.

Thanks!

**Comment by keiono** [comment] 2015-07-27 18:30
The cy.json() exports both Style and network topology in a single JSON.  Instead, Cytoscape Desktop handle those as two separate files.  Also, Cytoscape desktop can export both Styles and networks, but cannot read Cytoscape.js CSS-like styles because it is VERY different from Styles for Cytoscape desktop.  This is a current limitation in this feature.

**Comment by maxkfranz** [comment] 2015-07-27 18:51
@nandankita To clarify: Importing styles into Cy desktop will probably not be possible.  The model of Cy desktop for style is analogous to a very simple stylesheet:

```
node {
  ...
}

edge {
  ...
}
```

Since Cy.js can support stylesheets with an arbitrary number of selector blocks and Cy desktop has no notion of selectors, compatibility for styles from Cy.js-to-Cy3 is not really possible.

You could try making your stylesheet very, very simple and putting `cy.style().json()` into a style JSON exported by Cy3.  No guarantees, though.

As for separation of JSONs from Cy.js, it's all in what you call:

- `cy.json()` : whole graph state
- `cy.style().json()` : stylesheet only
- `cy.elements().jsons()` : graph elements only

**Comment by maxkfranz** [comment] 2015-07-27 18:51
Closing for now as this seems to be OK for @nandankita

**Closed by maxkfranz** 2015-07-27 18:51 UTC

**Comment by nandankita** [comment] 2015-07-27 20:44
Yeah it's good for me. Thank you so much for your help and explanation.

**Comment by keiono** [comment] 2015-09-03 17:39
I've pushed changes for Cytoscape 3.3.0 development branch.  I confirmed that new version reads both outputs from:

* ```cy.json()```
* ```cy.elements().jsons()```

Style conversion from Cytoscape.js to Cytoscape 3.x is way too complicated and not implemented (yet?).

You can try the nightly build if you try this new feature before 3.3.0 release:

* [Cytoscape 3 nightly build](http://code.cytoscape.org/jenkins/job/cytoscape-3-gui-distribution/lastSuccessfulBuild/org.cytoscape.distribution$cytoscape/)

**Comment by bramson** [comment] 2019-03-04 03:11
I know it's a few years later, but I tried loading a JSON that was generated by NetworkX and I got the same blank error message shown in the first screenshot.  Is there still no way to get Cytoscape to open my standard JSON file?

**Comment by maxkfranz** [comment] 2019-03-04 14:26
@bramson Would you please post the problematic JSON file here in order to help reproduce the issue?  What version of the Cytoscape desktop app are you using?

**Comment by maxkfranz** [comment] 2019-03-04 14:29
@bramson  Here's the link to report a bug in the Cytoscape desktop issue tracker: https://cytoscape.org/bug-report.html
