### ISSUE TITLE
Bypasses cleared on application of new stylesheet 

### ISSUE THREAD

**Issue by gulian** [cytoscape/cytoscape.js#1436] opened 2016-06-29 15:11 UTC
Hi, 

First, thanks for your great work !

I'm updating to Cytoscape 2.7.3 and I'm having trouble with my graph style. Compounds node seems to have trouble to reload styles when moving in and out nodes.

I'm using `move()` to define hierarchy between nodes : `node.move({ parent: parent.id });`

But my node style seem's to be reinitialized and looks like this: 

> ![capture d ecran 2016-06-29 a 16 55 49](https://cloud.githubusercontent.com/assets/487387/16457109/9b220750-3e1a-11e6-86af-88fe6a8bbd1f.png)

Instead of this: 

> ![capture d ecran 2016-06-29 a 16 55 55](https://cloud.githubusercontent.com/assets/487387/16457121/a41de270-3e1a-11e6-9938-9219414cfc05.png)

Same issue when i'm trying to remove node from another one with the style is lost : `node.move({ parent: null });` : 

> ![capture d ecran 2016-06-29 a 16 58 40](https://cloud.githubusercontent.com/assets/487387/16457166/ca35b42e-3e1a-11e6-82c3-1517281111ee.png)

But when I click on a non styled node, the style appears on the `mousedown` event.
> ![output2](https://cloud.githubusercontent.com/assets/487387/16457595/67170ab2-3e1c-11e6-8ba6-53606ca66b8b.gif)

Another glitch appear when clicking on nodes. Exemple : 
> ![output](https://cloud.githubusercontent.com/assets/487387/16457419/bc4cc540-3e1b-11e6-9de8-3b1ae7660f36.gif)
(The correct background size is the bigger one and appears on the mouse down event)

Not sure if it's related but edges are plugged at the center of the node instead of the border of the node.

Have you any idea or clues to investigate on theses issue ?

I'll try to reproduce it in a small and portable environment to help.

Best regards, 

Gulian

**Comment by gulian** [comment] 2016-06-29 15:26
Update: I've try to update to 2.6.12

Batching isn't working (fail on `endBatch()'), got theses errors : 
![capture d ecran 2016-06-29 a 17 22 41](https://cloud.githubusercontent.com/assets/487387/16458085/2946775c-3e1e-11e6-9c25-52c0b9065329.png)
![capture d ecran 2016-06-29 a 17 22 16](https://cloud.githubusercontent.com/assets/487387/16458086/2948b03a-3e1e-11e6-9e43-e7756e5b9069.png)

Without batching, everything is working properly, but I really need it for performance reasons ...

**Comment by maxkfranz** [comment] 2016-06-29 17:28
Re. compounds -- I played around on the debug page on master/2.7.4 and can't reproduce this.  If you can reproduce the issue, please make a small demo so a patch can be validated against it.  You could probably just fork this demo a bit: http://jsbin.com/gist/5b192c88616af2f75344?output

Re. `.batch()` in 2.6, I don't know how you reproduced this case, but we certainly have apps using 2.6 with `.batch()` without issue.  Since 2.6 is superseded by 2.7, there won't be any patches to 2.6.

Re. edges -- see https://github.com/cytoscape/cytoscape.js/issues/1199

**Comment by gulian** [comment] 2016-06-30 07:44
Hi, 

Thanks for answering so quickly. 

I might have reproduce my batch related issues : [JSBin](http://jsbin.com/nohomusico/1/edit?js,output)

The result is not the same when using batch or not.

Maybe I'm using it in the wrong way ?

**Comment by maxkfranz** [comment] 2016-06-30 18:44
Try the snapshot : http://js.cytoscape.org/download/cytoscape.js-snapshot-d87303970d-1467312213397.zip

Let me know if it works for you or if you have any issues with it.  

Thanks

**Comment by maxkfranz** [comment] 2016-07-05 14:26
@gulian Is it working for you?  Planning on releasing today

**Comment by gulian** [comment] 2016-07-06 08:43
Hi,

Sorry for the late answer. 

I am unfortunately not available to test it until monday. 

But I Will tell you as soon as possible. 

Regards, 

Gulian

**Comment by maxkfranz** [comment] 2016-07-07 19:28
@gulian OK, if you could look at it on Monday that would be great.  I want to release soon because of https://github.com/cytoscape/cytoscape.js/issues/1445 ...

**Comment by gulian** [comment] 2016-07-11 09:23
Hi @maxkfranz, 

The good news are : 
- Batch seems to work better, no more error in console, and this is a great great news (~20 seconds without batching, ~2 seconds with) 
- Nothing seems to be broken more

I still having issues on compounds nodes, when moving it in and out from other nodes (they are loosing styles). Do you want me to create another issues, or do we continue on this one ? 

I'll try to reproduce it on a small JSBin quickly.

**Comment by gulian** [comment] 2016-07-11 12:35
I finally succeed to reproduce the issue with a few lines of code (Firefox, Safari & Chrome) : http://jsbin.com/quricilavu

Here a screen capture, just in case : 
![kitten_groups](https://cloud.githubusercontent.com/assets/487387/16730688/a6e34cee-4774-11e6-96f0-e05cff0747c9.gif)

**Comment by maxkfranz** [comment] 2016-07-11 16:58
OK, can you create a separate issue for that problem?

I'm closing this one, since its issue is resolved.

**Closed by maxkfranz** 2016-07-11 16:58 UTC
Labels: bug

**Comment by gulian** [comment] 2016-07-12 07:48
Ok thanks.
