### ISSUE TITLE
Node body styles incorrectly cached (regression)

### ISSUE THREAD

**Issue by somedmguy** [cytoscape/cytoscape.js#2356] opened 2019-04-15 21:57 UTC
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : new in 3.5.3
- Browser/Node.js & version : firefox

**Current (buggy) behaviour**

Node body properties are caching the first value and using it for all nodes.

**Desired behaviour**

Each node gets its own style.

**Minimum steps to reproduce**

Change the cytoscape import for http://jsbin.com/fiqugiq to https://unpkg.com/cytoscape@3.5.3/dist/cytoscape.min.js
See all cats

**Comment by maxkfranz** [comment] 2019-04-16 19:46
Some might say that more cats is a feature, not a bug...  Joking aside, I think this patch should resolve it.  You can try the attached snapshot or build from master.

[3.5.4-snapshot1.zip](https://github.com/cytoscape/cytoscape.js/files/3086621/3.5.4-snapshot1.zip)

**Comment by maxkfranz** [comment] 2019-04-16 19:54
Closing for now.  If you find another case where this is not completely fixed, feel free to re-open.

**Comment by maxkfranz** [comment] 2019-04-17 14:25
I'm re-opening this issue for now so it has more visibility within the issue list.

**Comment by bakeyevrus** [comment] 2019-04-20 14:27
It happened to me also for 3.4.5 release

**Closed** 2019-04-24 14:20 UTC
Labels: bug
