### ISSUE TITLE
Background image is clipped when `background-clip` is set to `none`

### ISSUE THREAD

**Issue by jri** [cytoscape/cytoscape.js#1865] opened 2017-06-19 17:56 UTC
The node (gray ellipse) height is set to `20px`. The background image (blue circle) is 40 px high. Canvas size is big enough (e.g. 400x500px).

The background image is clipped although `background-clip` is set to `none`.

![screen shot 2017-06-19 at 19 33 10](https://user-images.githubusercontent.com/120337/27297691-3703fb88-5526-11e7-9102-98486bd4e940.png)

The background image is expected to be not clipped.

Try the fiddle:
https://jsfiddle.net/sh0a4w5p/1/

Tested with Cytoscape 3.1.2.

**Comment by jri** [comment] 2017-06-20 13:17
Hint: the mentioned fiddle uses a SVG image. The clipping appears also with PNG images.

![screen shot 2017-06-20 at 15 15 33](https://user-images.githubusercontent.com/120337/27334991-5beb1b34-55cb-11e7-9c53-54126b54fde2.png)

**Comment by maxkfranz** [comment] 2017-06-20 13:30
This is expected behaviour.  Because of how caching is done, you can't draw anything beyond a node's bounding box.  The clipping property is useful for non-rectangle shapes.

See https://github.com/cytoscape/cytoscape.js/issues/1782

**Comment by jri** [comment] 2017-06-20 13:44
> Because of how caching is done, you can't draw anything beyond a node's bounding box.

I can't acknowledge that.

Try this modified fiddle. It uses a graph with just one node:

https://jsfiddle.net/sh0a4w5p/2/

Here NO clipping appears. The background image definitely exceeds the node's bounding box.

But strangely this works ONLY if the canvas is wide enough (at least 310px or so).

To check it change the fiddle's result frame width and press Run again.

![screen shot 2017-06-20 at 15 25 34](https://user-images.githubusercontent.com/120337/27335479-d480d542-55cc-11e7-9b81-da85ffad5a01.png)

To me this is the expected behavior and a must-have possibly not only for my application.

**Comment by maxkfranz** [comment] 2017-06-20 13:54
That's also expected behaviour.  There are two tiers of caching.  Depending on the state of the caches and some runtime performance metrics, the cache may or may not be used.  The cache is used most of the time, and that's causes the restriction in draw area.  So in general, you can't draw anything beyond a node's bounding box.

We've already considered usecases that may need to draw beyond that.  That's why https://github.com/cytoscape/cytoscape.js/issues/1782 exists.  If you'd like to use that feature faster than we can prioritise it, then please feel free to make a pull request.

Thanks for your feedback.

**Comment by jri** [comment] 2017-06-20 14:16
Now I understand 2 things:
* in general, you can't draw beyond a node's bounding box at the moment
* in future this restriction might vanish (#1782)

But what you say regarding caching basically means: sometimes you CAN draw beyond the bounding box, and IF you can depends on the caching state, which is completely intransparent to the developer.

Possibly it would developers give less odd experience if they NEVER can draw beyond the bounding box, and if the docs for `background-clip` would be more clear.

Thank you for the explanations!
I appreciate your work very much!

**Comment by maxkfranz** [comment] 2018-03-05 17:56
Closing, as this should be addressed by #1782.

**Closed by maxkfranz** 2018-03-05 17:56 UTC
