### ISSUE TITLE
Transitions on 'display:none' elements can cause invisible edges to be drawn

### ISSUE THREAD

**Issue by somedmguy** [cytoscape/cytoscape.js#1525] opened 2016-09-16 01:19 UTC
I've seen two problems involving hidden elements and transitions.
1) The transition can cause the item to be drawn temporarily
2) On Firefox, the renderer could throw an exception and lock up cytoscape. 

Here are a couple of stack traces for the Firefox problem
![image](https://cloud.githubusercontent.com/assets/21342204/18572466/9a3ba010-7b70-11e6-82ec-6e0d465821cc.png)
![image](https://cloud.githubusercontent.com/assets/21342204/18572473/a8217cd6-7b70-11e6-8d66-c64e25860ea8.png)

Appending ':visible' to the selectors for the styles related to the transitions solved the problems.  Hopefully this can all be fixed by #1522

**Comment by maxkfranz** [comment] 2016-09-16 18:03
Have you noticed if this happens for you on just `display: none` elements, or does it also happen on others like `opacity: 0` or `visibility: none`?

Would you please paste one of your transition style blocks (from your stylesheet) that causes problems?

I don't think #1522 will be necessary to fix this, because it looks like a texture cache issue -- but I've updated #1522 to also elide animation style updates for hidden elements.

Thanks

**Comment by somedmguy** [comment] 2016-09-17 17:31
Here's a gist that should show the problem
https://gist.github.com/anonymous/fb4d659d9318f71516f4a42e360fecb6

To see the problems I mentioned:
1. tap a node to select it
2. right-click it to make it disappear
3. tap the background to unselect it (this will cause its edges to reapper)
4. try dragging the background (this will freeze cytoscape in firefox)

If you switch to visibility:hidden instead of display:none, then the node reappears as well in step 3, but firefox remains working in step 4.

**Comment by maxkfranz** [comment] 2016-09-20 17:36
There are two issues here:

(1) Animations can cause hidden edges to be drawn.

(2) Firefox JS engine throws exception on 0 dimension `c2d.drawImage()` calls #1529

Re. (1), I've added `.visible()` checks in the low-level draw functions for nodes and edges.  This would have caused a performance regression in <=2.6, but >=2.7 doesn't seem to be affected more than +/- 1% from my testing.

Re. (2), there are extra guards added so bb=0 draw requests are nops.  Firefox seems to be the only browser affected -- other browsers just translate to nops themselves without issue -- and it's affected only in very particular Cy.js usecases.

**Comment by maxkfranz** [comment] 2016-09-20 17:36
Try the snapshot : http://js.cytoscape.org/download/cytoscape.js-snapshot-626950f772-1474392597513.zip

Let me know if it works for you or if you have any issues with it.  

Thanks

**Comment by somedmguy** [comment] 2016-09-21 00:53
Using the snapshot, I removed all of the ':visible' modifiers and have not seen any problems.

**Comment by maxkfranz** [comment] 2016-09-21 14:23
Great; closing

**Closed by maxkfranz** 2016-09-21 14:23 UTC
Labels: bug
