### ISSUE TITLE
Some elements disappearing on zoom and pan

### ISSUE THREAD

**Issue by min-metal** [cytoscape/cytoscape.js#1591] opened 2016-10-30 20:11 UTC
The layer cache fills in elements in a layer even if the element is outside the bounds of the layer.  This happens only when the default number of layers is set to one.

OP follows:

---

Cytoscape version: 2.7.10
Chrome 54,
Safari 10

I don't know if you will be able to reproduce it or not but I have experienced some nodes disappearing sporadically on zoom/pan. They do re-appear again if you click on any other node that's still visible, and if you do `cy.$('node')` they are still in memory.

The nodes I'm using have svg backgrounds, but problem still occurs without background.

**Comment by dpekkle** [comment] 2016-11-03 23:08
Also ran into this. Were you using dynamically added nodes? For me it was only happening to the most newly added nodes (though I don't know what determined the cutoff point for newness).

cy.redraw and other such functions have no effect.

However for some reason updating the data attribute of any node temporarily fixes the issue, so my hacky fix was to use setInterval to update a 'fake' attribute in one of the nodes.

**Comment by min-metal** [comment] 2016-11-04 03:58
Yeah, I was dynamically adding new nodes, redraw didn't work for me either. My hack was to re-update the position of one of the node on pan/zoom, ( I used lodash's debounce to optimize it ). LOL.

**Comment by maxkfranz** [comment] 2016-11-09 20:13
@dpekkle @min-metal Does this happen for edges or just nodes?  It's probably an issue in the layer or element texture caches.

You can invalidate those caches (as a temporary workaround hack using private APIs) by `cy.renderer().data.lyrTxrCache.invalidateElements( elesToClean )` and `cy.renderer().data. eleTxrCache.invalidateElement( eleToClean )`.

I'll look into this, but I need a relatively minimal example that reproduces it.  Can you reproduce the issue on one of the demos on js.cytoscape.org with a few lines of code to modify the graph similar to how you are in your apps (adding/removing elements etc.)?

**Comment by maxkfranz** [comment] 2016-11-09 20:14
Also is Firefox also affected, or is this a Blink/Webkit-only issue?

**Comment by dpekkle** [comment] 2016-11-10 03:38
Firefox is also affected. Can't say for edges.

Here's a modification of the compound demo http://embed.plnkr.co/7st3eBJeXrw3xB8yrXw8/

Tap on background to create nodes, then zoom/pan. 

Added code:

```
cy.on('tap', function(event)
{
	var evtTarget = event.cyTarget;
	if (evtTarget === cy) //tap on background
	{
		cy.add(
		{
			data:
			{
				id: cy.nodes().size() + 1,
			},
			group: "nodes",
			renderedPosition: event.cyRenderedPosition,
		});
		}
});

```

**Comment by maxkfranz** [comment] 2016-11-11 20:23
@dpekkle Does this affect normal graphs or only compound graphs?

**Comment by dpekkle** [comment] 2016-11-11 22:06
Removed the parents to check, and yes its all graphs.

**Comment by maxkfranz** [comment] 2016-11-14 17:19
It looks like the issue is this:

> The layer cache fills in elements in a layer even if the element is outside the bounds of the layer. This happens only when the default number of layers is set to one.  The offending line looks like it assumed that there would be layer expanding and merging, which didn't make it into the current version of the cache.  Merging is logged in a separate issue now: https://github.com/cytoscape/cytoscape.js/issues/1604 

Try the snapshot : http://js.cytoscape.org/download/cytoscape.js-snapshot-7f970a8cf1-1479143597633.zip

Let me know if it works for you or if you have any issues with it.  

Thanks

**Comment by dpekkle** [comment] 2016-11-15 05:12
Works fine for me, thanks.

**Comment by min-metal** [comment] 2016-11-15 08:12
Yep, works for me as well. Thanks

**Comment by maxkfranz** [comment] 2016-11-15 16:16
Great; closing

**Closed by maxkfranz** 2016-11-15 16:16 UTC
Labels: bug

**Comment by Granddevv** [comment] 2019-10-31 16:01
Hi,
I am facing the above issue.
What's the solution?

The solution - above link is not working.
Please let me know if you can.
Thank you.

**Comment by binDongKim** [comment] 2019-11-27 08:54
I'm facing the same issue as well. Some edges disappear on zooming randomly.

**Comment by maxkfranz** [comment] 2019-11-28 21:50
Please provide a reproducible test case, including:

- Browser version
- OS version
- A code sample that reproduces the issue.  [A JSBin](http://jsbin.com/fiqugiq) can be forked to easily provide a code sample.

If you can provide a reproducible test case for the latest version of the library, then create a new issue for it and follow the issue template.
