### ISSUE TITLE
In some cases compound bounds are not rendered properly in unstable branch 

### ISSUE THREAD

**Issue by metincansiper** [cytoscape/cytoscape.js#1779] opened 2017-04-13 16:19 UTC
Hi,
Please see the demo below:
[cytoscape.js-demo.zip](https://github.com/cytoscape/cytoscape.js/files/920170/cytoscape.js-demo.zip)

In this demo I used cytoscape.js code that I build from the unstable branch. 
I set the node labels with the following code segment:
```js
       'content': function(ele) {
             ele.width(); // This call breaks the compounds in unstable branch
	      return ele.id();
         }
```
In this demo I changed the parent of node #d with the following code segment. 
```cy.$('#d').move({parent: 'a'})``` 

After performing this operation the compound bounds of node #a are rendered non properly (They are rendered properly again when we drag node #a). I realized that this problem occurs if I call ```ele.width()``` inside the function which determines the label of the nodes (I suppose that ```ele.width()``` calls ```ele.updateCompundBounds()``` internally and this is the main reason of the problem). 

Also, I realized that this problem occurs when we use the code from cytoscape.js unstable branch but it does not occur when we use the latest released cytoscape.js code by including the following script
```<script src="http://cytoscape.github.io/cytoscape.js/api/cytoscape.js-latest/cytoscape.min.js">```

Therefore, I think that this problem does not occur in master branch.

**Comment by maxkfranz** [comment] 2017-04-13 20:15
You shouldn't be reading style properties in the stylesheet.  You've created a cyclic dependency.

**Comment by metincansiper** [comment] 2017-04-17 09:10
@maxkfranz okey thanks for your answer. 

I need to truncate node labels so that they fit into nodes. Therefore, I need to have node width inside the function where I set node content. 

For example a node looks like the following when the label truncation is disabled

![capture](https://cloud.githubusercontent.com/assets/6534865/25084671/810a4ce2-2366-11e7-8aab-19f75edfcb74.PNG)

It seems like following when it is enabled

![capture2](https://cloud.githubusercontent.com/assets/6534865/25084686/920592ea-2366-11e7-9ae4-bbcef69f6ac8.PNG)

Is there a way of having this feature without breaking cytoscape.js functionality?

**Comment by maxkfranz** [comment] 2017-04-17 15:54
Yes, just don't use a function in the stylesheet.

Truncate the text before you init Cytoscape by using cut-off values based on the dimensions you later set for nodes in the stylesheet.

But you may be better off to just use the built-in features to improve the text styling.

**Comment by metincansiper** [comment] 2017-04-17 21:07
Thanks for the answer. However, in our application both node labels and node dimensions can be changed dynamically by the users. Therefore, it seems that I cannot do in that way.

**Comment by ugurdogrusoz** [comment] 2017-04-18 08:13
Doesnt look like built-in features can do truncation with ellipses (...) I wonder if it would be difficult to add this feature as a built-in one.

**Comment by maxkfranz** [comment] 2017-04-18 13:56
That's been considered before.  It's too expensive to calculate text dimensions for that on each style/bounds update.  The main case where it's practical if you use predetermined text and predetermined node sizes, and that means you'd have to do it all in the app level before add/init.

If the issue with the cyclic dependency in the stylesheet is resolved, then I'll close the issue.  If the problem is not resolved, then please re-open.

**Closed by maxkfranz** 2017-04-18 13:56 UTC
