### ISSUE TITLE
Style hash collision

### ISSUE THREAD

**Issue by pkmnfrk** [cytoscape/cytoscape.js#2494] opened 2019-08-07 19:47 UTC
**Issue type**
Bug report

**Environment info**

- Cytoscape.js version : 3.8.2
- Browser/Node.js & version : Chrome 75 (Win 10), Firefox 68.0.1 (Win 10)

**Current (buggy) behaviour**

This seems like a regression of #2348 

Node styles:
 * width, height: label
 * shape: round-rectangle

When rendering nodes with such styles under the preset layout, it draws borders weirdly, as though the css border-radius property is set to use different widths than heights. I'm not 100% sure on the root bug, but I have observed:

* Elements that look okay until you zoom in, which then look warped
* Elements that look warped, until you zoom in
* Elements that look okay until you click on them, and then they look warped.

Note that I'm specifically referring to the border, not the content or edges or anything. Also, it only seems to happen with preset layout.

**Desired behaviour**

The borders to look good at all zoom levels/scenarios

**Minimum steps to reproduce**

0. Go to https://jsbin.com/vaxefo/edit?html,js,output
1. Observe that Test 2 looks weird 
![image](https://user-images.githubusercontent.com/1333816/62652287-0af2e900-b929-11e9-9ee2-ccb1dd3e957e.png)
2. Observe that Test 1 and Test 3 look fine
3. Zoom in on Test 3
4. Observe that Test 2 now looks okay, but Test 3's border looks warped
![image](https://user-images.githubusercontent.com/1333816/62652313-1ba35f00-b929-11e9-9f8c-1514827db9d3.png)
5. Observe that Test 1 always looked okay

Other notes
 * Using the jsbin as reference, the observed behaviour seems to change based on different factors:
 * * The size of the elements (longer labels seem to trigger more severe issues)
 * * The position of the elements (try tweaking the `hoffset` variable at the top to bigger or smaller numbers)
 * * The size of the viewport (try changing the size of the div on the html tab). At 400px, it is as I showed above. At 600px, Test 3 looks okay. But, if you make the label longer, then it comes back

**Comment by maxkfranz** [comment] 2019-08-09 20:32
It's not a regression, but it is related to #2348 in that there is a style hash collision for your particular stylesheet.  The problem is that the final body hash evaluates to the same value, probably because the 'label' values are small and the xor operation is applied twice for the same value.

In the console:

```
cy.nodes().map(n => n[0]._private.styleKeys.nodeBody)
(3) [4231470307, 3568664259, 4231470307]
```

Note the same key at indices 0 and 2 -- test3 and test2.

I have an in-progress branch that has test cases and tweaks for making hashing more robust for the sorts of values that we have for style properties, but I haven't had time to complete it.  I don't know whether the changes in that branch would resolve the issue without further changes or whether I'll have enough time to complete it in the short-term.  However, I could push the branch to Github for public review and improvement.

**Comment by maxkfranz** [comment] 2019-08-09 20:40
I've rebased the branch to the current unstable branch and pushed it to Github: https://github.com/cytoscape/cytoscape.js/commits/hash

**Comment by maxkfranz** [comment] 2019-08-14 15:49
@pkmnfrk  It looks to be resolved on the hash branch for your example.  Take a look and let me know whether it works for you.

[3.9.1.-snapshot1.zip](https://github.com/cytoscape/cytoscape.js/files/3502150/3.9.1.-snapshot1.zip)

**Comment by maxkfranz** [comment] 2019-08-19 19:08
I'm closing this issue so that it can make it into 3.9.1, but let me know if there are further issues.

**Closed** 2019-08-19 19:08 UTC
Labels: bug
