### ISSUE TITLE
Severe performance degradation with edge arrows in firefox

### ISSUE THREAD

**Issue by somedmguy** [cytoscape/cytoscape.js#2367] opened 2019-04-17 17:40 UTC
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : >= 3.3.0
- Browser/Node.js & version : Firefox 66.0.3 (64-bit)

**Current (buggy) behaviour**

Over time, Firefox takes longer and longer to draw edge arrows such that even a modestly sized graph of 30 nodes can become unusable.

**Desired behaviour**

Draw quickly

**Minimum steps to reproduce**

https://jsbin.com/lacicozeco/
Drag nodes around, and it becomes noticeably choppier over time.  This does not happen in chrome, or with the 3.2 line of cytoscape (change the link to cytoscape@3.2.22), or with target-arrow-shape set to "none".

**Comment by maxkfranz** [comment] 2019-04-18 14:49
I can't reproduce this on any of my machines.  It's probably a regression in Firefox, and it may be dependent on the hardware or the OS.

I've seen those sorts of issues before in different browsers, and usually an issue gets fixed relatively quickly by a browser vendor if you post an issue on their bug tracker.  However, they may expect you to isolate the issue as a minimal reproducible test page --- which means they may want a page without Cytoscape.js.  But that may be difficult.

I suggest filing a bug in [Bugzilla](https://bugzilla.mozilla.org/home) and cross-referencing it with links here.  Make sure you specify all your system specs, because those probably play a role in reproducing this type of issue.  Include OS, OS version, exact browser version, CPU, graphics card, graphics driver. If it's an all-in-one device like a laptop, include the make and model.

Try to see if they're receptive with your existing demo.  If not, you may have to do some digging to isolate the root cause.

**Comment by somedmguy** [comment] 2019-04-18 16:28
Yeah, I agree it's probably a bug in Firefox, and I shouldn't have expected it to be system independent.

But it doesn't happen with cytoscape 3.2, so something must have changed between 3.2 & 3.3 to expose this.  I was hoping the source could be identified and an acceptable alternative put in.  Since you can't reproduce it, I guess the identification falls on me.

**Comment by somedmguy** [comment] 2019-04-19 18:53
I approached this from two directions

1. git-bisect pointed me at 0733599682ac8b117aa726b5f7041c494cb91bf4 as the first commit to exhibit the slowdown.

2. I used Firefox dev tools to see where it was spending most of its time, and that was definitely doing canvas updates in drawArrowShape().

Unfortunately, the commit is rather large and I couldn't find any obvious intersection between that and the results of (2).  You're much more familiar with the code-base than I, though, so I would appreciate it if you took a look.

Moving on, I took a closer look at the drawArrowShape() function.  It seemed likely, given the nature of the problem (slows over time, canvas operations as culprit), that some canvas component was persisting between draw cycles and growing in complexity every time it was used.  And there is in fact a cache of Path2D objects used for drawing the arrows.  I found that either disabling paths entirely (```enablePaths = false;``` in canvas/index.js) or commenting out the cache in drawArrowShape() solved the problem.  Would you be willing to allow the renderer options to disable either of these?

**Comment by maxkfranz** [comment] 2019-04-23 21:15
> Unfortunately, the commit is rather large and I couldn't find any obvious intersection between that and the results of (2). You're much more familiar with the code-base than I, though, so I would appreciate it if you took a look.

Those changes would only seem to be indirectly related at best.

> Moving on, I took a closer look at the drawArrowShape() function. It seemed likely, given the nature of the problem (slows over time, canvas operations as culprit), that some canvas component was persisting between draw cycles and growing in complexity every time it was used. And there is in fact a cache of Path2D objects used for drawing the arrows. I found that either disabling paths entirely (enablePaths = false; in canvas/index.js) or commenting out the cache in drawArrowShape() solved the problem. Would you be willing to allow the renderer options to disable either of these (assuming a better fix can't be found)?

No, that's not something that will be exposed in the library.  Nothing that is related to `Canvas` or `Context2D` should be API.  If you want to disable it, you should set window.Path2D = null` as the first line of your app before even your dependencies run.

The cache should only ever be one path object per arrow.  It should not grow with time, and the browser should render a shape faster with a path cache than without one.

It sounds like Firefox has a regression w.r.t. `Path2D`.

**Comment by mohd-akram** [comment] 2020-02-12 21:38
`window.Path2D = null` doesn't work. `window.Path2D = undefined` does.

The problem seems to be fixed by commenting out `context.beginPath()` and `context.closePath()` surrounding the `shapeImpl.draw` calls in `drawArrowShape`. `shapeImpl.draw` already calls `beginPath` and `closePath` (at least based on `drawPolygonPath`), so the outer calls don't seem necessary.

**Comment by maxkfranz** [comment] 2020-02-21 20:36
@somedmguy, would you be able to confirm that @mohd-akram's patch addresses this issue for you?

**Comment by somedmguy** [comment] 2020-02-22 02:19
Unfortunately, that's easier said than done at the moment, but I'll give it a try when I get back into the office on Monday.

**Comment by maxkfranz** [comment] 2020-02-24 15:45
It would be great if you would be able to verify some time this week.  We shouldn't rush a release before we can fully verify that the patch resolves the issue.

**Comment by mohd-akram** [comment] 2020-02-24 16:29
Are you unable to reproduce this @maxkfranz? You can check my [repo](https://github.com/mohd-akram/languages) where I came across the issue. The last commit has the fix and the one before is missing it.

**Comment by somedmguy** [comment] 2020-02-25 00:52
Max wasn't able to reproduce it, as he says in the first reply to this issue.  I think it's Windows only.

I lost access to outward facing Windows Firefox, but managed to reproduce both the issue & the fix on an internal system.

Thumbs up from me.  It was a good find.

**Comment by maxkfranz** [comment] 2020-03-11 17:08
Great, I'll plan to release on Monday

**Closed** 2020-03-18 15:14 UTC
Labels: browser-bug
