### ISSUE TITLE
Edge between two edges (or node and edge), edges inside nodes/edges (recursive encapsulation)

### ISSUE THREAD

**Issue by Konard** [cytoscape/cytoscape.js#1217] opened 2016-01-10 16:01 UTC
I`m working on project (https://github.com/Konard/LinksPlatform) that uses associative model of data.
For example this platform (as database) allows to store egdes between edges. And there is no difference between edges and nodes, all are links (pairs of references to other two links - source & target). Also because link consists of two links this creates a fractal which can be used to store sequences or entire graphs (networks) insite one link.

So my question is it possible to visualize something like this using cytoscape.js ? And if not, is it easy to extend/modify cytoscape.js for that task?

Node to node, node to edge:
![links](https://cloud.githubusercontent.com/assets/1431904/12222385/0357855a-b7cc-11e5-8b28-04abc14388dc.png)

Node to node, node to edge, **edge to edge**:
![links-edge-to-edge](https://cloud.githubusercontent.com/assets/1431904/12222387/1b316678-b7cc-11e5-9cca-2d4e20a2ef40.png)

Sequence, fractal, recursive encapsulation:
![12](https://cloud.githubusercontent.com/assets/1431904/12222396/51fcc102-b7cc-11e5-9bf9-d5a0be840e16.png)

I actually tried to change example (http://jsbin.com/gist/5b192c88616af2f75344) like this:
```JavaScript
edges: [
      { data: { id: 'ad', source: 'a', target: 'd' } },
      { data: { id: 'eb', source: 'e', target: 'b' } },
      { data: { id: 'adeb', source: 'ad', target: 'eb' } } // Added this edge
    ]
```
But added edge didn`t show up.

**Comment by maxkfranz** [comment] 2016-01-11 17:42
This is a duplicate of #959

**Comment by maxkfranz** [comment] 2016-01-11 17:44
You would have to create intermediary nodes to simulate hyperedges, as hyperedges are not supported natively yet.  It's not such a simple feature to implement, because it would affect large parts of the API -- like algorithms, traversing, etc.

**Comment by Konard** [comment] 2016-01-11 18:33
This is not a duplicate, because described above does not match definition of hyperedge direclty. Hyperedge is N to N connection, edge is 1 to 1. Link is also 1 to 1 connection, but difference is that each one (of these 1s) ara also links (or edges), and there is no separate verticies type. For example link that starts from itself and ends with itself is a point, or actually a verticle. The actual needed feature is to allow source and target of edges to reference other edges (not only nodes).

**Comment by maxkfranz** [comment] 2016-01-11 23:52
My mistake.  If you want not hyperedges but edge-edge edges, I'm not sure whether that would make sense.  One of the basic premises of graph theory is that edges connect *nodes*.  Whereas algorithms and traversal etc. can be made to make sense with hyperedges, my intuition is that edge-edge edges could not.

**Comment by Konard** [comment] 2016-01-12 13:21
> One of the premises of graph theory is that edges connect nodes.

**Comment by maxkfranz** [comment] 2016-01-13 13:52
I've spoken to others in the Cytoscape team about this.  This would be far more difficult than the hyperedges implementation.  As I said before, a basic premise of graph theory is that edges connect *only nodes*.  Allowing edges to connect to edges breaks that premise, and completely breaks the model.

Cytoscape.js is not just a visualisation tool, it has a sophisticated graph theoretic model and accompanying algorithms.  We can't break 90%+ of the functionality of the library to accommodate a single non-graph-theory usecase.

Your examples are database entity-relationship models.  N-ary relationships are represented by entities, in databases and in your diagramme.  Similarly, you should be using separate nodes to represent n-ary relationships if you want to use Cytoscape.js.  You can do this in your app-level code or you can create an extension.

If you can point us toward reputable journal published papers that define edge-edge edges in *graph theory*, then perhaps we can revisit this.

For now, I'm closing this and you can use intermediary nodes.

Thanks for your feedback

**Closed by maxkfranz** 2016-01-13 13:52 UTC
Labels: question

**Comment by Konard** [comment] 2016-01-13 20:38
http://iacis.org/iis/2009/P2009_1301.pdf

**Comment by maxkfranz** [comment] 2016-01-13 20:46
Those are ER/database models, not graph theoretic models.

**Comment by Konard** [comment] 2016-01-13 20:48
Ok there are other possible solutions:
1. Possibility to remove arrow from edge (just a straight line between nodes) So the edge is always an node with exacly two edges (one in and one out), and both edges should be synchronized (continue the same path).
2. Possibility to embed another cytoscape graph inside the node. So that node will have inner structure. For example to embed a small visualization with two nodes and one edge inside other node.

Can you please point out are these options possible with cytoscape?

**Comment by maxkfranz** [comment] 2016-01-14 15:54
You should be able to do (1) with an intermediary node between the edges so that the edge-edge edge points towards the intermediary node.  (2) is just compound nodes.

**Comment by Konard** [comment] 2016-01-15 08:01
Implemented example with compound nodes (2). https://linksplatform.github.io/cytoscape.html (`taphold` to expand/collapse).

**Comment by Konard** [comment] 2016-01-15 16:13
Implemented examples:
1. http://linksplatform.github.io/cytoscape-intermediate.html 
2. http://linksplatform.github.io/cytoscape-compound.html
(`taphold` to expand/collapse)

**Comment by Konard** [comment] 2016-03-25 20:56
http://gojs.net/latest/samples/linksToLinks.html (implementation at go.js)

**Comment by maxkfranz** [comment] 2016-04-04 21:15
Go.js is a generic charting lib, Cytoscape.js is for *graph theory*

As far as I'm aware, there is no concept of edge-edge edges in graph theory.

**Comment by jri** [comment] 2018-12-14 01:02
@maxkfranz talks about graph model.
@Konard talks about associative model, which is inherently different.
Although I'm a Cytoscape.js user myself and looking for a visualization/interaction solution for the associative model too, Cytoscape.js might not be proper foundation for that.

**Comment by jri** [comment] 2019-01-02 16:39
I've created a Cytoscape extension that allows edges to be connected to other edges, according to the Associative Model of Data:  
https://github.com/jri/cytoscape-edge-connections
