### ISSUE TITLE
[performance] Canvas renderer redraw timeout 

### ISSUE THREAD

**Issue by philippe46** [cytoscape/cytoscape.js#1105] opened 2015-09-23 23:23 UTC
Canvas renderer redraw timeout gets too high after some time page was inactive or tab being switched. Cytoscape.js renderer sets timeout for 1 sec which make graph zooming and panning unresponsive. 
We should rewrite logic of timeout calculation to make it more responsive

src/extensions/renderer.canvas.drawing-redraw.js line 254 of master

**Comment by maxkfranz** [comment] 2015-09-28 13:43
That call is made only if (1) you system is not capable of keeping up with 60fps for the given graph or (2) a request to render has been made that would result in greater than 60fps (i.e. unnecessary frames).

I can not reproduce the behaviour you describe.  Switching back to a previously inactive tab allows for resuming of drawing as normal.  Note that inactive tabs themselves will not update -- this is expected behaviour in a browser.  Please post an example that clearly reproduces the behaviour you describe.

You may also want to try unstable/2.5, as it uses a slightly different rendering mechanism.

**Comment by philippe46** [comment] 2015-09-30 11:48
This call (setting timeout) is used frequently during some time after 
switching to the tab that was inactive for some time in Google Chrome 
(which is strange). Chrome limits timeouts to 1 sec when page is 
inactive. When you switch page back after some time: zooming, panning 
becomes laggy for 6-10 secs. I've tried to make timeout zero and 
rendering become better, but few lags remain after page switch. Seems 
like it's a Google Chrome issue, because Firefox make it better after 
changing timeout to zero.

Will add video later.

**Comment by jsalankey** [comment] 2015-09-30 19:09
I have encountered the same thing for a while. Generally it happens worst after the tab has been inactive for a fairly long period of time.

**Comment by maxkfranz** [comment] 2015-10-01 14:51
The video would be useful, but so would a small code demo.  I can't reproduce this at all on my machines.

Those timeouts should get triggered only if your app code or the user does something that requires a redraw.

**Comment by maxkfranz** [comment] 2015-10-19 15:15
@philippe46 Any updates?  Can you reproduce this on the unstable/2.5 branch?  Thanks

**Comment by maxkfranz** [comment] 2015-10-23 21:16
I'm going to close this for now as I can't reproduce it and the changes to 2.5 should fix it if it is indeed an issue

**Closed by maxkfranz** 2015-10-23 21:16 UTC

**Comment by philippe46** [comment] 2015-12-11 00:41
It's not your problem, @maxkfranz
Problem belongs to my update code that's fire on timer. Browser throttles down timers that causes probem. Switching my code to WebWorker. Sorry for distrurbing.
