### ISSUE TITLE
cy.json() omitting numbers in style definitions

### ISSUE THREAD

**Issue by webwizrd** [cytoscape/cytoscape.js#1510] opened 2016-08-30 20:15 UTC
Small bug when saving out the state of the graph with .json() I believe:

graph contains style definition with selector:

`
{        selector: 'node[status=1.0]',
          style: {
            'background-color': '#2FEFEF'
}`

Result from .json() only contains `selector: 'node[status=]'`, omitting the number in the selector.
With selector and <=, its even stranger: `'node[status<=1.0]'` becomes `'node[<=status]'`

**Comment by maxkfranz** [comment] 2016-09-01 14:46
Try the snapshot : http://js.cytoscape.org/download/cytoscape.js-snapshot-0dd3906ce4-1472741089058.zip

Let me know if it works for you or if you have any issues with it.  

Thanks

**Comment by webwizrd** [comment] 2016-09-03 15:47
Partially fixed: numbers now show up in selectors for all " = " selectors. The one with "<=" still doesn't work correctly, but extracts as "selector":"node[<=status]"

**Comment by maxkfranz** [comment] 2016-09-07 14:50
2.7.9 needs to be released, and I can't reproduce this issue on master.  Closing this for now.  If there are still issues with this, please comment on the issue and it will be addressed in a later release.

**Closed by maxkfranz** 2016-09-07 14:50 UTC
Labels: bug
