### ISSUE TITLE
calculating betweenness

### ISSUE THREAD

**Issue by mktonn** [cytoscape/cytoscape.js#1058] opened 2015-08-28 08:37 UTC
I was using the function betweennessCentrality() for the following (undirected) network:

cy.add([
{group: "nodes", data: {id: "n0", name: "0"}},
{group: "nodes", data: {id: "n1", name: "1"}},
{group: "nodes", data: {id: "n2", name: "2"}},
{group: "nodes", data: {id: "n3", name: "3"}},
{group: "nodes", data: {id: "n4", name: "4"}}
]);

cy.add([

{group: "edges", data: {id: "e0", source: "n0", target: "n1"}},
{group: "edges", data: {id: "e1", source: "n1", target: "n2"}},
{group: "edges", data: {id: "e2", source: "n1", target: "n4"}},
{group: "edges", data: {id: "e3", source: "n2", target: "n3"}},
{group: "edges", data: {id: "e4", source: "n3", target: "n4"}}
]);

and the function was calculating a betweenness of 8 for n1, but shouldn't it be 7?
Thanks!

**Comment by maxkfranz** [comment] 2015-08-28 19:16
Duplicate of https://github.com/cytoscape/cytoscape.js/issues/1032

**Closed by maxkfranz** 2015-08-28 19:16 UTC
Labels: duplicate
