### ISSUE TITLE
Node colors change depending on zoom level

### ISSUE THREAD

**Issue by laiaga** [cytoscape/cytoscape.js#2360] opened 2019-04-16 16:19 UTC
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.5.3
- Browser/Node.js & version : 66.0.2 (64-bit)

I noted the same behavior on Linux Mint and Windows 10. 

Moreover, the bug is not present if I use cytoscape 3.5.2 or any earlier version.

**Current (buggy) behaviour**

The bug occurs when I specify different classes for my nodes, and those classes have a different background-color. 
All nodes, regardless of their class, share the same color, which is always the first background-color I've defined.

**e.g.** with the following cytoscape style, my nodes will appear PaleVioletRed
```
     style: [{
            selector: "node",
            style: {
              "background-color": "PaleVioletRed",
              "label": "data(id)"
            }
          },
          {
            selector: ".colored",
            style: {
              "background-color": "teal",
            }
          }
        ]
```

However, if I zoom in, the color of the nodes change. Here I have observed different behaviours and can't tell what triggers them:
- first case, only the nodes of the class "colored" change color, actually becoming "teal"
- second case, all nodes change color regardless of their class, all becoming "teal"

Note that I have not noticed this second behaviour when I had more than 1 class.

**Desired behaviour**

Nodes have the color associated with their class, or the default color if they have no class defined. If I change the class of a node at runtime its color changes accordingly.

**Minimum steps to reproduce**

1. Create a graph with 2 nodes, one of which has a class (e.g. "colored") and the other has none. 
2. Define a default style for nodes with a background-color
3. Define a class style for the class "colored" with another background-color

The issue should be apparent. 

Here is [a jsbin example](https://jsbin.com/purubovope/edit?js,output).

**Comment by maxkfranz** [comment] 2019-04-16 19:53
Very probably a duplicate of the following:

Node body styles incorrectly cached (regression) #2356

See the referenced patch in that issue.  Feel free to re-open if the attached snapshot in the issue doesn't resolve things for you.

**Closed by maxkfranz** 2019-04-16 19:53 UTC
