### ISSUE TITLE
Box selection panning after some time

### ISSUE THREAD

**Issue by curupaco** [cytoscape/cytoscape.js#784] opened 2014-12-30 18:58 UTC
When using box selection, the graph starts to pan after some time.

Steps to reproduce:
- Access: http://jsbin.com/sahewozena/1/edit?js,output
- Add property boxSelectionEnabled: true
- Make a box selection and don't release the mouse button
- wait about 2 seconds
- move the mouse
The graph starts to pan

**Comment by maxkfranz** [comment] 2015-01-02 22:42
Odd.  I didn't see that on my local instance before publishing, but there were some issues with publishing the last x.y.z release.  I'll take a look; thanks

**Comment by maxkfranz** [comment] 2015-01-06 00:52
Adding to 2.3.8 milestone.  Given the severity of the issue, it may even merit its own release.

**Comment by danieljue** [comment] 2015-01-06 00:55
Thank you Max, we would really like to use this latest version of 2.3.7+, and this bug came up for us as well.

**Comment by bertomaniac** [comment] 2015-01-07 03:04
I'm using 2.3.4 and just tried this out in our environment and wasn't able to reproduce. Perhaps this bug was introduced in 2.3.5+?

**Comment by maxkfranz** [comment] 2015-01-08 18:02
Thank you for your patience, guys.  I've pushed a fix.  Please try it out and I'll push out the release ASAP.

Snapshot build: http://js.cytoscape.org/download/cytoscape.js-snapshot-16cf86597e-1420740052765.zip

**Comment by curupaco** [comment] 2015-01-08 18:32
Hi Max, thanks for your immediate attention on this issue.
I tested the snapshot in our application and on a simple demo from the site.

The issue with the box selection seems to be solved, but the pan stopped working.
Tried with both values in `boxSelectionEnabled`. 
Also checked if the pan was enabled with `userPanningEnabled()` and `panningEnabled()`, both returned `true`

**Comment by maxkfranz** [comment] 2015-01-08 21:42
OK.  That's actually a bit of a relief in a way, because I re-enabled a "magic" number condition in that build.  I'll take a look; thanks

**Comment by maxkfranz** [comment] 2015-01-08 22:00
Maybe this?

Snapshot: http://js.cytoscape.org/download/cytoscape.js-snapshot-4294a1643f-1420754382449.zip

**Comment by curupaco** [comment] 2015-01-09 10:37
Yep, this snapshot works perfectly. Thanks

**Comment by rockshandy** [comment] 2015-01-09 16:42
This fixes my issue too. There is sometimes a slight delay between when the shaded circle appears to indicate I clicked long enough to start panning, and switching to panning mode. Box selection starts instead sometimes if I move my mouse right after the panning indicator appears. Waiting a little longer after I click works as expected, and panning happens instead. This doesn't happen very often, but I wanted to mention it incase someone else observed this.

**Comment by maxkfranz** [comment] 2015-01-09 17:27
Ref: https://github.com/cytoscape/cytoscape.js/commit/4327f51c7257919db7b73b6647279bc7ab0c871c

Snapshot: http://js.cytoscape.org/download/cytoscape.js-snapshot-4327f51c72-1420824418477.zip

**Comment by maxkfranz** [comment] 2015-01-09 19:34
Previous update fixed the fast case that shows both UI indicators.  There is also the slow case, which is harder to time (i.e. must be precise at a later time).

**Comment by rockshandy** [comment] 2015-01-11 19:32
Seems to fix the issue I mentioned, thanks for the fix and quick turn around!

**Comment by maxkfranz** [comment] 2015-01-15 17:36
OK.  There's still a minor graphical glitch if the timing is slow but very precise.  Closing for 2.3.8 release.  

Ref: https://github.com/cytoscape/cytoscape.js/issues/800

**Closed** 2015-01-15 17:40 UTC
Labels: 1-high-priority, bug
